### ISSUE TITLE
[BUG] Everything become red

### ISSUE THREAD

**Issue by Mara-Li** [oleeskild/obsidian-digital-garden#1]
Testing on ipad.
Enabling the plugin transform all text in settings in red. 

In think there is a error in the plugin CSS.

**Comment by oleeskild** [comment]
Ah, thanks for picking that up. The styles.css was copied from a template, and I completely forgot to remove it. I've updated it by deleting the styles.css. It was not in use. Does it look better now?

**Comment by Mara-Li** [comment]
Deleting the css (dunno why it don't delete) repear this behavior!
