### ISSUE TITLE
Sidebar should be viewable on 13" screens

### ISSUE THREAD

**Issue by holgerhubbs** [oleeskild/obsidian-digital-garden#104]
Ole, thank you for your great plugin!
Somehow I don't have a local graph.

Any hint is appreciated:
https://www.notion.so/mindstream/Screenshot-for-Ole-2022-11-16-4debe859a9e042ce90f4fa641eccaa49

**Comment by oleeskild** [comment]
Did you figure out a way to fix it? I took a look at your site, and it's there:
![CleanShot 2022-11-17 at 12 56 49](https://user-images.githubusercontent.com/6201338/202440151-9ab03632-7b6a-4176-85a5-ab2823d61318.png)

Or maybe you are looking at it on a smaller screen. It doesn't pop up until you browser window has a width larger than 1490 px. I know that smaller laptops are currently too small, even when the browser is running fullscreen. 

But I was thinking about tweaking the design a bit so that it will be possible to view the graph on smaller screens as well.

**Comment by holgerhubbs** [comment]
Thank you for your reply!
So strange...

I am on a 13" Macbook Pro and I am pretty sure that I saw the local graph on the small screen, when I browsed your articles.

I made a screenshot of the browser window, it is 1395 @ 144 DPI (2790 @ 72 DPI).
Yes, on my 32" monitor I now see that everything is working!

Thank you for your help (-;

**Comment by oleeskild** [comment]
Awesome! I actually recently discovered that a 13" Macbook Pro is too small for the graph to show. I'll keep this issue open as a reminder to tweak the design so that it will also show on 13" screens.

**Comment by holgerhubbs** [comment]
Thank you Ole, yes it would be cool to have the graph view available.

On small screens:
- instead to disable this great feature, why not stack the blocks on top of each other?
- or to have an accordion (closed by default) with the Graph View.

Anyway, it's easy to have ideas, much harder to make them work (-;

PS: I signed up for https://ko-fi.com/holgerhubbs the service looks friendly and easy.

**Comment by Wensupu-Yang** [comment]
> Thank you for your reply! So strange...
> 
> I am on a 13" Macbook Pro and I am pretty sure that I saw the local graph on the small screen, when I browsed your articles.
> 
> I made a screenshot of the browser window, it is 1395 @ 144 DPI (2790 @ 72 DPI). Yes, on my 32" monitor I now see that everything is working!
> 
> Thank you for your help (-;

Hey Hollgerhubbs

I'm on 13" MBP and have the same issue and I discover if you change the display resolution to "More Space" the graph view does show-up. 
<img width="499" alt="Screenshot 2022-12-12 at 8 34 51 AM" src="https://user-images.githubusercontent.com/26530267/206998738-26d85601-f11e-4c97-91d4-0ba92f3b9031.png">

Hope this hack might be helpful, at least before oleeskild tweak the design. Thank you again for build such great tool.

**Comment by holgerhubbs** [comment]
Thank you Wensupu-Yang.

I personally don't like the "More Space" appearance, and I would like other people to be able to see the Graph.

**Comment by oleeskild** [comment]
I've released a [new version of the template](https://github.com/oleeskild/digitalgarden/releases/tag/1.28.0), where the sidebar now can be seen as long as your screen is 1400px or wider. 13" MacBooks is 1440px, so this should be enough.  ([How to update template](https://dg-docs.netlify.app/getting-started/06-updating-the-template/))
