### ISSUE TITLE
[Enhancement] Automatic sitemap.xml generation

### ISSUE THREAD

**Issue by ThatOtherAndrew** [oleeskild/obsidian-digital-garden#105]
Search engines like Google have trouble with when many pages are added, deleted or renamed. The search console provides two ways to fix this - individually request re-indexing for each note, or provide a sitemap.

I was wondering if it'd be possible for the plugin to handle this instead, by collating all the notes and assembling them into an XML sitemap on each publish with changes to URLs? It's not too complex a schema, and it would save a lot of manual labour.

**Comment by oleeskild** [comment]
Good idea! I've implemented it in the latest release. Note that you'll have to first update the plugin to the latest version before updating the template.

**Comment by ThatOtherAndrew** [comment]
Amazing, thank you very much!

**Comment by ThatOtherAndrew** [comment]
It appears the generated sitemap uses relative paths for `<loc>` tags, which is not recognised by Google's indexer. Would it be possible to prefix all paths with a domain?

![image](https://user-images.githubusercontent.com/26030336/205257079-f8b0136a-ca1b-4cac-b31d-e42ff484c994.png)

**Comment by oleeskild** [comment]
Thanks for pointing that out. I didn't know sitemaps required the full URL. 
I've released version 1.24.0 of the plugin. Updating the plugin, and the template will make the "Base URL" setting available to the sitemap.
If you've already set this setting, you will need to "touch" it once. For example by deleting the last character and adding it again, to trigger the update to the site. 


![Image](https://user-images.githubusercontent.com/6201338/206403257-facab275-6518-4832-beae-b2ef4c0e723b.png)
