### ISSUE TITLE
Links to headings do not work correctly

### ISSUE THREAD

**Issue by toburger** [oleeskild/obsidian-digital-garden#11]
In Obsidian the following gets rendered when a reference to a heading in a note specified:
![image](https://user-images.githubusercontent.com/728782/157697538-e77381a4-df7c-4205-9c68-fada0ef637b9.png)

The plugin output produces the following (I've updated some CSS stylings on my site):
![image](https://user-images.githubusercontent.com/728782/157697678-8d489909-ef60-40d3-9a19-d9c141b9eba9.png)

and the link points to:
`/notes/sanitaer-und-heizungsplanung-heizungssystem`

This should be:
`/notes/sanitaer-und-heizungsplanung/#heizungssystem`

And an `<a id="heading name">` is missing on the headings.

**Comment by oleeskild** [comment]
Do I understand you correctly in that this link now leads to a 404 page? If so this has been fixed in the latest releases. Try updating the plugin and republish the note. It should link to the correct page.

I have yet to implement linking to the actual header on the page, but it's on my todo list.

**Comment by toburger** [comment]
![image](https://user-images.githubusercontent.com/728782/158015121-2d71869c-632a-48f4-bcde-0ac60f9378c5.png)
I've also chosen to publish multiple notes to refresh all published pages.

Exactly, it produces a link where the `#title` is appended to the filename with `-title`.

**Comment by oleeskild** [comment]
Hmm, that's weird. Just to be sure: you are also using the latest version of the plugin itself, 2.3.1?

**Comment by toburger** [comment]
I wasn't reading your advice correctly about updating the plugin, sorry!
I was on Version 2.0.0, I've updated the plugin and now everything works fine! Thank you for the support and your patience!

**Comment by toburger** [comment]
> I have yet to implement linking to the actual header on the page, but it's on my todo list.

I'm totally fine with the current behavior. Thank you!
