### ISSUE TITLE
Feature file tree item list indicator

### ISSUE THREAD

**Issue by OvrAp3x** [oleeskild/obsidian-digital-garden#111]
When browsing items in the file tree, it can sometimes be "hard" to separate items from eachother, especially if items have long titles spanning more than one line.
see picture
<img width="225" alt="image" src="https://user-images.githubusercontent.com/14344702/204273381-b3d6d7d6-ab73-4194-b065-9b8a85aa0b86.png">

It would be good to have some sort of like "points" or something in front of the items like a - or something

- item1
- item2
- item3

If it was configurable that would be cool, but not neccessary

**Comment by oleeskild** [comment]
Great suggestion. I've just released version 1.21.0 of the template. The files now have a "note" icon in front of the titles, making it easier to separate the items. For now it's not configurable. 

The template can be updated by following the steps in the [documentation](https://dg-docs.netlify.app/getting-started/06-updating-the-template/). Let me know if it works as you expected 😄

**Comment by OvrAp3x** [comment]
Great! 
Thank you👍🍳
