### ISSUE TITLE
Add an option to disable slugify url

### ISSUE THREAD

**Issue by Mowd** [oleeskild/obsidian-digital-garden#114]
By commenting out the URL replacement, I can keep the original path and filename in the permalink,

```typescript
  let patternSlug = /[^a-zA-Z\d]+/g;
- string = string.replace(patternSlug, options.separator);
+ //string = string.replace(patternSlug, options.separator);
```

Also, I prefer to keep the string case instead of lowering them all, although Netlify forces all URL strings to be lowercase.
To resolve non-English URL problems refs #74, adding an option and letting users decide may be a good solution.
If users choose off, then keep all URLs without modifying them.

![image](https://user-images.githubusercontent.com/1097892/205029238-c47ba14a-ee18-4346-af61-01f554383163.png)

**Comment by oleeskild** [comment]
This was a great suggestion @Mowd . An easy way to get around the issue, without breaking backwards compatibility. I've released version 2.27.0 of the plugin, which now has this setting. I've tested it with Chinese characters and emojis, and it should fix the issue you are experiencing.
