### ISSUE TITLE
Outline of the headings of a note

### ISSUE THREAD

**Issue by f-mc2** [oleeskild/obsidian-digital-garden#118]
Hi Ole, thanks again for the beautiful plugin. The more I use it, the more I like it! While using it, I realized that, in Obsidian, it is possible to have an outline of all the headings of a given note in a menu on the right through the Outline Core Plugin. I think it could be useful to have something similar in the digital garden, with the option of activating it or not, in a framed environment like the local graph or the backlinks.

**Comment by oleeskild** [comment]
Great idea! This is something I'm working on, as part of implementing #73. I have a working version, but I need to figure out how it should look in combination with the other elements. I think it looks best when put on the top right. But it gets a bit crowded in the right pane if the local graph and the backlinks are also enabled. 
I'm thinking that I should perhaps move the backlinks pane to somewhere else. 
Do you have any suggestions of what you think would look best?

Here is a GIF of the current implementation:
![CleanShot 2022-12-07 at 13 41 53](https://user-images.githubusercontent.com/6201338/206182529-802def23-f207-4ff8-a17c-7788e11d91f4.gif)

**Comment by f-mc2** [comment]
I think the implementation in the GIF is essentially perfect!
I agree with [the comment in issue 73](https://github.com/oleeskild/obsidian-digital-garden/issues/73#issuecomment-1340947093) that suggests to put graphs on top of the outline.
Regarding backlinks, I personally do not use them, but I also think that having the 3 things on the right would not be that much of a problem. Thanks again for all the effort.

**Comment by oleeskild** [comment]
I've just released a new version of the plugin and the template, with support for table of contents. It has changed a bit from the GIF. The main difference being that I moved it beneath the graph. 
To use it, update the plugin first, before updating the template. Thanks for the suggestion 😄
