### ISSUE TITLE
Are Dataview inline queries supported?

### ISSUE THREAD

**Issue by oyale** [oleeskild/obsidian-digital-garden#122]
Hi! 
I've found this awesome plugin less than a week ago, and I love it. Congrats on your work, and thanks for sharing it.

I'm experiencing an issue, but I'm not sure if this is a feature request or a bug report.

The default Dataview queries works like a charm, but when I try to use an inline query, it is rendered as a monospaced text instead of evaluating the query. I'm currently experiencing this when trying to access the note metadata with both `` `=this.url` `` and `` `= this.url` ``

This is how it's rendered in Obsidian
![image](https://user-images.githubusercontent.com/25091358/207949532-c6d8c576-5c9b-4495-8b27-72788c4662b0.png)

This is the HTML output:

```html
<div class="content cm-s-obsidian">
      
        <h1>Kill Process Running on a Specific Port in Linux</h1>
      
      <p>From <code>= this.url</code></p>
<blockquote>
<h2 id="excerpt">Excerpt</h2>
<p>Want to kill the processes running on specific ports? No need to know the process ID or name. You can terminate a process based on the port number it is using.</p>
```
I'm aware of that the DataviewJS is not supported, and I reach out to their web to check if this functionality is part of it. They distinguish between _Dataview inline queries_ and _DataviewJS_ inline queries, so that makes me think that's not the case.

As pointed out, I'm not sure if this is a bug or a feature request, but I thought it was worth bringing it to your attention. 

Kudos to you!

**Comment by oleeskild** [comment]
Thank you for the kind words 😄 

I wasn't aware of this dataview feature, thanks for brining it to my attention!
I thought it would be simple to implement, but turns out rendering an inline query is not supported by the Dataview Plugin API, which is what the digital garden plugin uses behind the scenes. 
So unfourtunately it currently isn't possible to support. If a future version of dataview implements support for rendering inline queries via the plugin api, I'll be sure to add it to the plugin.

**Comment by oyale** [comment]
Thanks for the quick response!

I got curious and went in to take a peek at the Dataview API. I'm aware that I _don't know_ how your plugin implementation works, and that I may be talking nonsense, but... Is it possible that this functionality is exposed as [`evaluate`](https://github.com/blacksmithgu/obsidian-dataview/blob/a1588ed63c28555220bb32cb820a324fca3ca2e4/src/api/plugin-api.ts#L361)?

**Comment by oyale** [comment]
Disclaimer: I do not have any expertise with typescript. But now I can't help but try a solution :sweat_smile:  – would something like this make any sense?

```typescript
    async convertInlineDataViews(text: string, path: string): Promise<string> {
        let replacedText = text;
        const inlineDataViewRegex: RegExp = /`(=.+?)`/sg;
        const dvApi = getAPI();
        const matches = text.matchAll(inlineDataViewRegex);
        if (!matches) return;

        for (const queryBlock of matches) {
                const block = queryBlock[0];
                const query = queryBlock[1];
                const result = await dvApi.evaluate(query);
                if (result.successful) {
                    replacedText = replacedText.replace(block, result.value);
                }        }
        return replacedText;
    }

```
