### ISSUE TITLE
I can't deploy my site.

### ISSUE THREAD

**Issue by huhexian** [oleeskild/obsidian-digital-garden#123]
![image](https://user-images.githubusercontent.com/42113492/207994600-0224b7ef-a1aa-4e24-9567-ee8235ba2590.png)
can you tell me why?

**Comment by oleeskild** [comment]
I suspect you have the option "Let all frontmatter through" enabled in your plugin note settings, and one of your notes has a date field in the frontmatter that is not recognized by the template as a valid date. 
Try disabling this setting and see if that helps.

**Comment by oleeskild** [comment]
Were you able to fix it?
