### ISSUE TITLE
Can we optimize the problem that the Chinese title cannot be constructed?

### ISSUE THREAD

**Issue by Jeffreyone** [oleeskild/obsidian-digital-garden#125]
If the title is pure Chinese, the construction will fail. Fortunately, I found that it can be constructed normally as long as both Chinese and English are mixed. Then I need to add meaningless English to every note, which bothers me a lot

**Comment by oleeskild** [comment]
Yes we can. I've released version 2.27.0 of the plugin which introduces an option to disable "Slugify URL". I've created a page in the docs here: https://dg-docs.ole.dev/getting-started/05-other-settings/#slugify-note-url.
Disabling this should fix your issue 😄
