### ISSUE TITLE
New Template not updating on site

### ISSUE THREAD

**Issue by booksbeansboots** [oleeskild/obsidian-digital-garden#126]
Hi

I've just updated to the new template. It seems to have deployed OK. I have changed the name of my site from Digital Garden but the changes are not reflected in my site. I wondered if you could point me in the right direction please. This is my site: https://booksbeansboots.co.uk/ Many thanks. P.S. I'm also getting a message 'failed to update settings. Make sure you're connected to the internet' - which I am.

**Comment by oleeskild** [comment]
It seems you have reverted the update commit: https://github.com/booksbeansboots/bbbdg/commit/2c16a655734271d143aa74ec5d77870c9f2fe58c

Thererfore the site is in a bad state, and probably doesn't build on Netlify. You will probably see an error there. Try updating the template again, and see if it works better then 😄

**Comment by booksbeansboots** [comment]
Thanks for your help. All resolved now.
