### ISSUE TITLE
Problem with Theme Update and Pull Request

### ISSUE THREAD

**Issue by mettaseva** [oleeskild/obsidian-digital-garden#129]
Apologies for troubling you with this issue. I'm new to GitHub/Netlify, and it seems I've botched my attempt to update my ODG theme, based on your most recent [TOC Display](https://github.com/oleeskild/obsidian-digital-garden/issues/73#issuecomment-1353639055) and [Link Previews](https://github.com/oleeskild/obsidian-digital-garden/issues/83#issuecomment-1358498692) updates.

What needs to be done to resolve the problems displaying [HERE](https://github.com/mettaseva/digitalgarden/pull/1)?

To the best of my knowledge, I updated the plugin first, and then initiated the theme update as directed, but without success.

FWIW, I'm working in the Brave browser on Windows 11, in case this makes a difference.

With my thanks in advance,
Metta

**Comment by oleeskild** [comment]
I see that there are one file missing from the Pull Request. This typically happens when an older version of the plugin is used. Just to be sure: Can you verify that you have the 2.28.1 version installed? 

After that, can you try to delete your PR and the new branch, and then restart Obsidian? Let me know if you're get stuck.

**Comment by mettaseva** [comment]
Thank you very much, @oleeskild, for your prompt follow-up and feedback.
* I confirmed the current version 2.28.1 is installed.
* I successfully deleted my PR and manage to close and then delete the new branch.

After restarting Obsidian, I updated the template, and this was the resulting PR URL:
> [https://github.com/mettaseva/digitalgarden/pull/2](https://github.com/mettaseva/digitalgarden/pull/2)

The PR appeared to be successful (all checks passed), but when I checked the [deploy preview](https://deploy-preview-2--discoverynow.netlify.app/), the new TOC feature did not display on the home page or the "[Formatting Tests](https://deploy-preview-2--discoverynow.netlify.app/explore/formatting-tests/)" page where I inserted separate tests of the tiered headers.
* Am I missing something ~ or will the new TOC feature only display after the PR is finalized?
* If things are good as is, what do I need to do now to finalize this process? > Do I simply click "Merge Pull Request"?
* If things are **not** correct as is, how should I proceed?

**Comment by oleeskild** [comment]
Great! 
* The TOC feature needs to be enabled in the [note settings](https://dg-docs.ole.dev/getting-started/03-note-settings/#show-a-table-of-content-for-notes). By default it's turned off, so you won't see it in the preview.
* Yes, just click "Merge Pull Request" and the new template will be live on you site. You can then try [enabling the table of content feature](https://dg-docs.ole.dev/getting-started/03-note-settings/#show-a-table-of-content-for-notes) in the note setting in Obisidan. It should then appear on your site.

Let me know if you get it to work or not.
