### ISSUE TITLE
[FR] add "Back to Top", "Next", "Previous"

### ISSUE THREAD

**Issue by andrey-jef** [oleeskild/obsidian-digital-garden#133]
Situation:
- Reading the plugin new docs site on mobile, after having reached the end of a note, i have to scroll multiple times to go back to top, then click the hamburger menu button to display the left side bar, then click another note to continue reading

Suggestion:
- Add a floating button "Back to Top" when reaching the bottom of a note, so reader can quickly go top and open left side bar
- Or add a "Next" / "Previous" button at the bottom of a note, so reader can simply click when reaching the end of note, to continue reading on the next note in a folder

**Comment by oleeskild** [comment]
Good observation. What do you think about a third option: Making the header font-size a bit smaller and the search bar smaller so that the height of the navbar is lower. Then make the navbar sticky, so that it is always there on mobile?

**Comment by andrey-jef** [comment]
> Good observation. What do you think about a third option: Making the header font-size a bit smaller and the search bar smaller so that the height of the navbar is lower. Then make the navbar sticky, so that it is always there on mobile?

Aha. Agree. The navbar sticky would be an option too. Idk how much screen display it will take on a constraint screen asset like mobile web. But it surely enhance the reading experience

**Comment by oleeskild** [comment]
I've released a [new version of the template](https://github.com/oleeskild/digitalgarden/releases/tag/1.28.0), where the sticky navbar has been implemented for mobile devices. ([How to update template](https://dg-docs.netlify.app/getting-started/06-updating-the-template/))

**Comment by andrey-jef** [comment]
Thanks for implementing this. Much better reading experience with less action required to navigate within the vault. It makes lurking on the plugin docs pages as a joyful activity now 😁
