### ISSUE TITLE
Moved digital garden home note - content doubling up

### ISSUE THREAD

**Issue by axiomeval** [oleeskild/obsidian-digital-garden#14]
Hi - I moved my garden home note into another folder. Now content on that page has doubled up. If I move the note to a third location I get duplication of the content again - tripled up.

V2.4.0 of the plugin on latest Obsidian.

Any ideas?

Thanks.

**Comment by ThatOtherAndrew** [comment]
I've encountered this issue as well, a temporary fix would be to manually delete the old file - you'll find it under `src/site/notes` in your GitHub repository. I may be mistaken, but I believe tracking file name/path changes is on its way - would be worth leaving this issue open just in case.

**Comment by hxhc** [comment]
It seems that the operations only contains "git add", without "git rm --cached". So the old files will not be removed from the repo automatically.

**Comment by oleeskild** [comment]
As @ThatOtherAndrew mentioned: Deleting the file manually in the src/site/notes folder in your repository should do the trick.

Quick explanation to what is happening: When you add the dg-home:true attribute to your note it is added as part of a collection/list. This list will be looped through when generating the homepage. In practice this means that you can add this attribute to as many notes as you like, and they will all appear on top of each other on your homepage.

When you move a file in obsidian it is essentially the same as deleting it, and creating a new file (with identical content). Currently the only way to delete files when using plugin is to manually delete them from your repo. 

After the last update it should be a bit easier to know what files you should delete by looking in the "Publication Center" under the list "Deleted from vault".

I'm working on an update where the "Publish multiple notes" command deletes files to match your deleted files in your vault, as well as buttons in the publication center to make this easier. 

I'll report back here as soon as this is available!

**Comment by axiomeval** [comment]
Thanks all - that pointed me to the problem.

Great plugin by the way!

**Comment by oleeskild** [comment]
Thanks! Happy to hear you solved it.

I've just released version 2.6.0 which also supports deleting files. Either by using the "Publish Multiple Notes" command or using the "Delete notes from garden" button in the publication center. Hopefully will that make this problem happen less in the future.
