### ISSUE TITLE
Specify root directory for garden

### ISSUE THREAD

**Issue by timjore** [oleeskild/obsidian-digital-garden#142]
As a user that would like to manage my digital garden in my main Obsidian vault and keep all my published notes in a separate subdirectory, I would like to be able to manually configure a root directory for the garden. For example, my vault structure is:

- Resources
    - Garden
        - Note in Digital Garden.md

The same structure shows up in the filetree on the published site. I would like to be able to specify the location of the filesystem in my vault, like:

`Root Directory`: `Resources/Garden`

Then the filetree in the sidebar of the published site would show:

- Note in Digital Garden.md

in the root, and any subdirectories under Garden would then appear as subdirectories in the filetree.

**Comment by timjore** [comment]
@oleeskild Would it be possible to implement this as setting the Filetree root directory? It would really be nice to have the filetree start from a specified directory instead of the vault root.

**Comment by ludwikc** [comment]
That's exactly what I'm looking for here.

**Comment by Rinnray** [comment]
I'm also looking for something like this.

**Comment by Rinnray** [comment]
While setting things up and messing around I discovered that you can just use ´dg-path´ in the frontmatter as a slight workaround. 

It's a bit more work whenever you create a note since now you're gonna have to write `dg-path: File.md` in each note.
Then if you decide to make subdirectories inside the `Garden` directory (or whatever you name it), you'd have to write `Subdirectory/File.md`.

It's not as nice as having a global setting as the author mention, but it does the job until it's added (if ever).

**Comment by julesvirallinen** [comment]
I had the same issue, so I added a fix to the path rewrite that allows rewriting a folder to a blank path. 

now you can do a path rewrite 

`/garden:/` and it should work like above!

**Comment by Rinnray** [comment]
> I had the same issue, so I added a fix to the path rewrite that allows rewriting a folder to a blank path.
> 
> now you can do a path rewrite
> 
> `/garden:/` and it should work like above!

I don't know if I'm doing something wrong but I add this in the `Path Rewrie Rules`:
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/47090855/f2691e3c-ec6a-4da9-aaf6-ccae4c2ecded)

Then I have the `Home` note, which I expect to be by itself, like this (using the `dg-path` in the notes themselves):
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/47090855/e08d5a83-953e-46a5-ab11-1a89ed4c0c64)

But it still looks like this:
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/47090855/d9895668-a71c-418e-80dc-5a6e584b76b6)

**Comment by julesvirallinen** [comment]
@Rinnray I think I typoed the message above, checked my own and I have `garden:` as my setting, and it seems to work fine. 

I added this preview box under the rewrite rules so you can test them: 

with slash before: 
<img width="863" alt="CleanShot 2023-09-10 at 14 18 10@2x" src="https://github.com/oleeskild/obsidian-digital-garden/assets/4622905/fc040063-797f-4df6-8e69-3f43b6549534">

without slash before: 
<img width="510" alt="CleanShot 2023-09-10 at 14 18 37@2x" src="https://github.com/oleeskild/obsidian-digital-garden/assets/4622905/59462f52-e052-443f-9f8b-f47ad1fc13bf">

So try `garden:` and see if it works! I'll add a ticket to remove slashes before rules too, as that sounds like a bug!

**Comment by Rinnray** [comment]
> So try `garden:` and see if it works!

Yep! That seem to have worked! ^^
