### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by uroybd** [oleeskild/obsidian-digital-garden#150]
I think, support for timestamps can be a great enhancment since it's a garden, and we want to see things grow.

To achieve that we can have following settings for maximum flexibility:
1. A global toggle to show or hide timestamps
2. 2 fields to select which keys to be used from the frontmatter for updated and created timestamps.

If the user choose to show the timestamps, we will first attempt to get the timestamps from the frontmatter, in that doesn't exist, then from file's created and updated dates.

**Comment by oleeskild** [comment]
I agree. Timestamps would be a great addition. I think your suggestion would work very well.
