### ISSUE TITLE
Add support for tags in lines written in languages other than English

### ISSUE THREAD

**Issue by tonygrr** [oleeskild/obsidian-digital-garden#155]
Thank you for adding inline tagging support. But tags written in languages other than English are not supported.

![image](https://user-images.githubusercontent.com/72566774/211619475-6e624f11-5dcb-4e60-88d6-4f39db074d78.png)

**Comment by uroybd** [comment]
Shamelessly stole and slightly modified this pattern from [here](https://stackoverflow.com/questions/27342945/regex-for-matching-hashtags-in-any-language):

```
#[^\s!@#$%^&*()=+./,\[{\]};:'"?><]+
```

This pattern should cover the inline tags of any language.

**Comment by oleeskild** [comment]
Thanks for letting me know @tonygrr , and thanks for providing the regex @uroybd . I've released a fix in the latest version of the template.
