### ISSUE TITLE
In the generated site, when searching with Ctrl + K, the results are not complete

### ISSUE THREAD

**Issue by Gonglja** [oleeskild/obsidian-digital-garden#156]
Hello, oleeskild
     In the generated [site](https://glj0.netlify.app/), when searching with Ctrl + K, the results are not complete.

![20230111-144245.jpg](https://s2.loli.net/2023/01/11/cgLSR9Jp2zMCVPX.jpg)

**Comment by oleeskild** [comment]
Thanks for letting me know @Gonglja! I've released a fix for the template. Instructions for how to update it can be viewed here: https://dg-docs.ole.dev/getting-started/06-updating-the-template/

Let me know if that fixes it for you or not.

**Comment by Gonglja** [comment]
> 

Yes, I just updated and it shows up normally

thanks
