### ISSUE TITLE
Hastags conflicts with markdown attribute.

### ISSUE THREAD

**Issue by uroybd** [oleeskild/obsidian-digital-garden#164]
In content hashtag detection conflicts with markdown attrs. Here's the solution I found work (it also has the main regex properly escaped.

```js
// In .eleventy.js
.use(require("markdown-it-hashtag"), {
      hashtagRegExp: `[^\\s!@\\#\\$%\\^&\\*\\(\\)=\\+\\.,\\[\\{\\]\\};:'"\\?><]+`,
      preceding: "^|\\s\\{",
    })
```

**Comment by oleeskild** [comment]
Right, didn't think about that. Thanks for letting me know, and providing the solution! I've released a new version of the template with this fix.

**Comment by uroybd** [comment]
Optimized it a little.

```js
.use(require("markdown-it-hashtag"), {
      hashtagRegExp: `[^\\s!@\\#\\$%\\^&\\*\\(\\)=\\+\\.,\\[\\{\\]\\};:'"\\?><]+`,
      preceding: "^|(?!(\\{.*))|\\s",
     })
```

**Comment by oleeskild** [comment]
That doesn't seem to work, it will match the tag inside { #123abc} 🤔

**Comment by oleeskild** [comment]
And the last one seems to have broken tags inline. It only matches tags starting at the start of a line, and those with whitespace and an immediate "{" ahead of the "#". Trying to create a working regex, but this proved difficult when we need to discard "{ #123abc}" 😅

**Comment by oleeskild** [comment]
After some trial and error, I think this should work:

```
.use(require("markdown-it-hashtag"), {
            hashtagRegExp: `[^\\s!@\\#\\$%\\^&\\*\\(\\)=\\+\\.,\\[\\{\\]\\};:'"\\?><]+(?!(.*\\}))`,
            preceding: "^|\\s",
        })
```

Here I am doing a negative lookahead for (.*\}), meaning that a hashtag succeeded by a } on the same line will not match. 
It's still not perfect as any line with a "}" will not render the tag. i.e.
"#mytag some text }"

 But it's better than the current version. Keeping this open until we manage to create a working regex.

**Comment by oleeskild** [comment]
I think I fixed it by simply adding the markdown-it-attrs after the markdown-it-hashtag in the markdown-it plugin pipeline. It seems it's processed in reverse. So when we're looking for hastag, the attribute is already taken care of.

**Comment by oleeskild** [comment]
Hmm, that didn't work after all. I will look closer at this tomorrow.

**Comment by uroybd** [comment]
> That doesn't seem to work, it will match the tag inside { #123abc} 🤔 

No it has a negative lookahead in my latest example. Have to check more anyway.

**Comment by uroybd** [comment]
Fixed it here: https://github.com/oleeskild/digitalgarden/pull/45

Not in browser though, but after the markdown to HTML conversion.
