### ISSUE TITLE
Table of Contents [toc] renders out of order

### ISSUE THREAD

**Issue by meleu** [oleeskild/obsidian-digital-garden#169]
In the example below, even though my heading structure is not the most organized one, the resulting ToC is not what should be expected.

![image](https://user-images.githubusercontent.com/8508804/213805447-68d40b37-0cc1-4b91-86d0-44e61a255a0a.png)

See it alive here: https://meleu.netlify.app/notes/bug-report/

If it helps, here's the raw markdown file:
https://raw.githubusercontent.com/meleu/meleudotdev/master/notes/bug-report.md

**Comment by pawelel** [comment]
Couldn't reproduce the issue:
![image](https://user-images.githubusercontent.com/14290787/217522974-9069498d-fb58-4740-8ec3-db3b08344396.png)
But it might be already fixed.

**Comment by meleu** [comment]
@pawelel in your example your document structure is pretty well behaved.

Can you please test with this ~~crazy~~ content:
```md
# bug-report

## my h2

paragraph

#### my h4

paragraph

##### my h5

paragraph

### my h3

paragraph

#### another h4

paragraph

### another h3

paragraph

```

**Comment by shinanqu** [comment]
I haven't checked this specific example, but I would like to add, the TOC add on creates lists with these lines which are very close to each other. If the lines are close to each other, I think it means that the list lacks a parent and something is not as it's supposed to be. And the Digital Garden thus also has unexpected results.

To solve the issue, mark everything with the narrow lines and unindent it once (SHIFT + TAB). The narrow lines disappear and the list looks much cleaner with a visually better hierarchy. Now Digital Garden should be able to read it.
