### ISSUE TITLE
[Feature request] MathJax support

### ISSUE THREAD

**Issue by ThatOtherAndrew** [oleeskild/obsidian-digital-garden#17]
Currently, [MathJax](https://www.mathjax.org/) syntax between `$dollar signs$` and `$$double dollar signs$$` do not work, meaning mathematical expressions do not render correctly. Support for this would be awesome!

---
<sup>Sidenote: Would you prefer for issues to be opened here, or at the [template repository](https://github.com/oleeskild/digitalgarden)?</sup>

**Comment by oleeskild** [comment]
Nice catch! It seems inline mathjax was not enabled by default. Double dollar sign was only working when it was on a single line. 
I've updated the template (https://github.com/oleeskild/digitalgarden/releases/tag/1.9.0) to also support inline math.

I think creating issues at this repo would be best :)

**Comment by ThatOtherAndrew** [comment]
Very helpful, thank you! However, MathJax doesn't seem to be rendering in admonitions - would it be possible to add support for that please?

**Comment by oleeskild** [comment]
Fixed! :)

**Comment by ThatOtherAndrew** [comment]
Awesome, thank you!
