### ISSUE TITLE
Faild to build

### ISSUE THREAD

**Issue by ChristinaHyh** [oleeskild/obsidian-digital-garden#170]
It seems that after first deploy (successfully) and pulishing some posts, it will get an error.
I got the error on the Netlify when Manage theme with Digital Garden Plug-in in obsidian.
Deploy error: "Build failed due to a user error: Build script returned non-zero exit code: 2"
I have try many times, but I don't know why. 

As for build command, I set as 'npm install && npm run build', for publish directory, 'dist' is employed.

The deploy log is as follows:

> 9:58:44 PM: build-image version: a2d22d22e4555d1ef0a972ed14a0a4b366ad20c4 (focal)
> 9:58:44 PM: build-image tag: v4.16.3
> 9:58:44 PM: buildbot version: 211709fe0bb687fe4fe2ebbb0a0d7258aa6e265c
> 9:58:44 PM: Building without cache
> 9:58:44 PM: Starting to prepare the repo for build
> 9:58:45 PM: No cached dependencies found. Cloning fresh repo
> 9:58:45 PM: git clone --filter=blob:none --no-checkout https://github.com/ChristinaHyh/TARDIS
> 9:58:45 PM: Preparing Git Reference refs/heads/master
> 9:58:45 PM: Parsing package.json dependencies
> 9:58:46 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'npm install && npm run build' versus 'npm run build' in the Netlify UI
> 9:58:47 PM: Starting build script
> 9:58:47 PM: Installing dependencies
> 9:58:47 PM: Python version set to 2.7
> 9:58:47 PM: v16.19.0 is already installed.
> 9:58:47 PM: Now using node v16.19.0 (npm v8.19.3)
> 9:58:47 PM: Enabling Node.js Corepack
> 9:58:47 PM: Started restoring cached build plugins
> 9:58:47 PM: Finished restoring cached build plugins
> 9:58:48 PM: Attempting Ruby version 2.7.2, read from environment
> 9:58:48 PM: Using Ruby version 2.7.2
> 9:58:49 PM: Using PHP version 8.0
> 9:58:49 PM: Started restoring cached corepack dependencies
> 9:58:49 PM: mv: cannot move '/opt/build/cache/.node/corepack' to '/opt/buildhome/.node/corepack': No such file or directory
> 9:58:49 PM: Finished restoring cached corepack dependencies
> 9:58:49 PM: No npm workspaces detected
> 9:58:49 PM: Started restoring cached node modules
> 9:58:49 PM: Finished restoring cached node modules
> 9:58:49 PM: Bypassing sha validation. Running pre & post install scripts
> 9:58:49 PM: Installing npm packages using npm version 8.19.3
> 9:58:53 PM: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> 9:58:53 PM: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> 9:58:53 PM: npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
> 9:58:54 PM: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> 9:58:58 PM: added 622 packages, and audited 623 packages in 9s
> 9:58:58 PM: 80 packages are looking for funding
> 9:58:58 PM:   run `npm fund` for details
> 9:58:58 PM: 13 vulnerabilities (2 moderate, 8 high, 3 critical)
> 9:58:58 PM: To address issues that do not require attention, run:
> 9:58:58 PM:   npm audit fix
> 9:58:58 PM: Some issues need review, and may require choosing
> 9:58:58 PM: a different dependency.
> 9:58:58 PM: Run `npm audit` for details.
> 9:58:59 PM: npm packages installed
> 9:58:59 PM: Started restoring cached go cache
> 9:58:59 PM: Finished restoring cached go cache
> 9:59:00 PM: Installing Go version 1.19.5 (requested 1.19.x)
> 9:59:05 PM: unset GOOS;
> 9:59:05 PM: unset GOARCH;
> 9:59:05 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.19.5.linux.amd64';
> 9:59:05 PM: export PATH="/opt/buildhome/.gimme/versions/go1.19.5.linux.amd64/bin:${PATH}";
> 9:59:05 PM: go version >&2;
> 9:59:05 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.19.5.linux.amd64.env"
> 9:59:05 PM: go version go1.19.5 linux/amd64
> 9:59:05 PM: Detected 1 framework(s)
> 9:59:05 PM: "eleventy" at version "1.0.2"
> 9:59:05 PM: Installing missing commands
> 9:59:05 PM: Verify run directory
> 9:59:05 PM: Section completed: initializing
> 9:59:07 PM: ​
> 9:59:07 PM:   Netlify Build                                                 
> 9:59:07 PM: ────────────────────────────────────────────────────────────────
> 9:59:07 PM: ​
> 9:59:07 PM: ❯ Version
> 9:59:07 PM:   @netlify/build 29.5.1
> 9:59:07 PM: ​
> 9:59:07 PM: ❯ Flags
> 9:59:07 PM:   baseRelDir: true
> 9:59:07 PM:   buildId: 63cd41138fb9fb24f03cbfa3
> 9:59:07 PM:   deployId: 63cd41138fb9fb24f03cbfa5
> 9:59:07 PM: ​
> 9:59:07 PM: ❯ Current directory
> 9:59:07 PM:   /opt/build/repo
> 9:59:07 PM: ​
> 9:59:07 PM: ❯ Config file
> 9:59:07 PM:   /opt/build/repo/netlify.toml
> 9:59:07 PM: ​
> 9:59:07 PM: ❯ Context
> 9:59:07 PM:   production
> 9:59:07 PM: ​
> 9:59:07 PM:   1. build.command from netlify.toml                            
> 9:59:07 PM: ────────────────────────────────────────────────────────────────
> 9:59:07 PM: ​
> 9:59:07 PM: $ npm install && npm run build
> 9:59:08 PM: up to date, audited 623 packages in 765ms
> 9:59:08 PM: 80 packages are looking for funding
> 9:59:08 PM:   run `npm fund` for details
> 9:59:08 PM: 13 vulnerabilities (2 moderate, 8 high, 3 critical)
> 9:59:08 PM: To address issues that do not require attention, run:
> 9:59:08 PM:   npm audit fix
> 9:59:08 PM: Some issues need review, and may require choosing
> 9:59:08 PM: a different dependency.
> 9:59:08 PM: Run `npm audit` for details.
> 9:59:08 PM: > web@1.0.0 build
> 9:59:08 PM: > npm-run-all get-theme build:*
> 9:59:08 PM: > web@1.0.0 get-theme
> 9:59:08 PM: > node src/site/get-theme.js
> 9:59:09 PM: > web@1.0.0 build:eleventy
> 9:59:09 PM: > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
> 9:59:09 PM: [11ty] Writing dist/404/index.html from ./src/site/404.njk
> 9:59:09 PM: [11ty] Writing dist/sitemap.xml from ./src/site/sitemap.njk
> 9:59:09 PM: [11ty] Writing netlify/functions/search/data.json from ./src/site/lunr.njk
> 9:59:09 PM: [11ty] Writing dist/index.html from ./src/site/index.njk
> 9:59:09 PM: [11ty] Writing dist/ice-9/christina-s-tardis/index.html from ./src/site/notes/ICE-9/Christina's TARDIS.md (njk)[11ty] Writing dist/ice-9/how-to-use-digital-garden/index.html from ./src/site/notes/ICE-9/How to use Digital Garden.md (njk)
> 9:59:09 PM: [11ty] Copied 1 file / Wrote 6 files in 0.20 seconds (v1.0.2)
> 9:59:10 PM: > web@1.0.0 build:sass
> 9:59:10 PM: > sass src/site/styles:dist/styles
> 9:59:11 PM: Error: Expected '.      ╷
> 9:59:11 PM: 25422 │     content: '\A\9\9'';      │                        ^
> 9:59:11 PM:       ╵
> 9:59:11 PM:   src/site/styles/theme.9843a84f.css 25422:24  root stylesheet
> 9:59:11 PM: ERROR: "build:sass" exited with 65.
> 9:59:11 PM: ​
> 9:59:11 PM:   "build.command" failed                                        
> 9:59:11 PM: ────────────────────────────────────────────────────────────────
> 9:59:11 PM: ​
> 9:59:11 PM:   Error message
> 9:59:11 PM:   Command failed with exit code 1: npm install && npm run build (https://ntl.fyi/exit-code-1)
> 9:59:11 PM: ​
> 9:59:11 PM:   Error location
> 9:59:11 PM:   In build.command from netlify.toml:
> 9:59:11 PM:   npm install && npm run build
> 9:59:11 PM: ​
> 9:59:11 PM:   Resolved config
> 9:59:11 PM:   build:
> 9:59:11 PM:     command: npm install && npm run build
> 9:59:11 PM:     commandOrigin: config
> 9:59:11 PM:     publish: /opt/build/repo/dist
> 9:59:11 PM:     publishOrigin: config
> 9:59:11 PM:   functionsDirectory: /opt/build/repo/netlify/functions
> 9:59:11 PM:   redirects:
> 9:59:11 PM:     - from: /api/*      status: 200      to: /.netlify/functions/:splat    - from: /*      status: 404      to: /404  redirectsOrigin: configCaching artifacts
> 9:59:11 PM: Started saving node modules
> 9:59:11 PM: Finished saving node modules
> 9:59:11 PM: Started saving build plugins
> 9:59:11 PM: Finished saving build plugins
> 9:59:11 PM: Started saving pip cache
> 9:59:11 PM: Finished saving pip cache
> 9:59:11 PM: Started saving emacs cask dependencies
> 9:59:12 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
> 9:59:11 PM: Finished saving emacs cask dependencies
> 9:59:11 PM: Started saving maven dependencies
> 9:59:11 PM: Finished saving maven dependencies
> 9:59:11 PM: Started saving boot dependencies
> 9:59:11 PM: Finished saving boot dependencies
> 9:59:11 PM: Started saving rust rustup cache
> 9:59:11 PM: Finished saving rust rustup cache
> 9:59:11 PM: Started saving go dependencies
> 9:59:11 PM: Finished saving go dependencies
> 9:59:12 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
> 9:59:12 PM: Failing build: Failed to build site
> 9:59:12 PM: Finished processing build request in 27.954s

Very appreciate for getting the help from you, thank you.

**Comment by ChristinaHyh** [comment]
I know. When I change the Theme to Blue Topaz, the deploy will be failed.

**Comment by oleeskild** [comment]
Thanks for reporting this. This has been fixed in the latest version of the template. Try [updating the template](https://dg-docs.ole.dev/getting-started/06-updating-the-template/), and see if it works better then. Let me know if that fixes it

**Comment by ChristinaHyh** [comment]
It works! Very appreciate for it.

**Comment by oleeskild** [comment]
🎉
