### ISSUE TITLE
Can't unpublished notes by Digital Garden Center

### ISSUE THREAD

**Issue by ChristinaHyh** [oleeskild/obsidian-digital-garden#171]
When I open the Digital Garden Center, there's no list of published notes and unpublished notes. So I don't know how to unpublished the notes without delete the notes directly in Github Repos.

Could you please guide me about this. Very appreciate for it.

**Comment by oleeskild** [comment]
Just to make sure, you are clicking the plus button to the left of the "Published" header? Can you send a screenshot?

**Comment by ChristinaHyh** [comment]
<img width="572" alt="2023-01-23_135723" src="https://user-images.githubusercontent.com/48902684/213974519-33e87afe-abda-43dc-b168-85f1685a030c.png">


Yeah, I can't see any notes in the center, and when I click on the button of "Delete notes from garden", there's nothing happened (I have removed the dg-publish: true attribute in the fronmatter). So I am not sure whether it's due to my incorrect operation. 

Thank you

**Comment by oleeskild** [comment]
Hmm ,weird 🤔 Haven't seen this before, so I'm not sure what's going on. Could you open the developer tools in Obsidian, open the console, and see if any errors appear when opening the publication center? Or when you are expanding any of the lists?

Here's a GIF of how to find the console, in case you haven't opened it before:
![CleanShot 2023-01-23 at 08 49 42](https://user-images.githubusercontent.com/6201338/213989193-aba0fa85-f492-435c-a71c-618ada7593e3.gif)

**Comment by ChristinaHyh** [comment]
<img width="1063" alt="2023-01-23_155937" src="https://user-images.githubusercontent.com/48902684/213990598-ab9c4e2f-3de7-4b58-92e5-6f89956ea90f.png">
Sorry for I can't understand these information, so I uploaded the picture. Please check the picture. Thank you!

**Comment by oleeskild** [comment]
No worries, a picture was what I needed. Just forgot to write it 😅 
Hmm okay. Seems the plugin can't find your repo. Can you verify that your GitHub repo name and your username in the digital garden settings are correct? And that they don't contain any spaces before or after them?

**Comment by ChristinaHyh** [comment]
Yes, I think it is right. Because I can use the command in obsidian to publish the notes and I can see them in my github repo. 🤔

**Comment by oleeskild** [comment]
I think I’ve found the issue. When the publication center checks your files in github, it assumes your branch name is «main». I see that your branch is named «master». I’ll hopefully get a fix out later today, so that you may use whatever name you prefer. The plugin should just look at whatever you have set as default.

**Comment by ChristinaHyh** [comment]
It works now! So wonderful! Thank you very much!

**Comment by oleeskild** [comment]
🎉
