### ISSUE TITLE
Adapt README for Initial Setup

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#175]
It seems necessary to adapt paragraph 3. of the Initial Setup from the README since Netlify is still mentioned there.

![Screenshot_2023-01-26-17-12-09-677_com.github.android~3.jpg](https://user-images.githubusercontent.com/61867589/214888445-a5a8fc86-204a-4635-ad97-4d0714b21903.jpg)

**Comment by oleeskild** [comment]
Thanks! Fixed ⚙️
