### ISSUE TITLE
Dataview generated links that have an ampersand (&) are broken

### ISSUE THREAD

**Issue by shervinsahba** [oleeskild/obsidian-digital-garden#184]
Normal links parse ampersands correctly. For example `[[Updates & About]]` goes to the slug `updates-and-about` as desired. However, links generated by dataview parse to `updates-and-amp-about`.

Thanks for the amazing plugin :)

![](https://i.imgur.com/szSug6s.png)

**Comment by oleeskild** [comment]
Thanks for reporting this @shervinsahba! I've just relased a fix for this in the template. [Updating the template](https://dg-docs.ole.dev/getting-started/06-updating-the-template/) should fix the issue. Let me know if you get it working or note 😄

**Comment by shervinsahba** [comment]
It's working now. Thanks!
