### ISSUE TITLE
Does the "Manage Site Template" dialog need updating?

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#185]
The text in the "Manage Site Template" dialog box still refers to Netlify (penultimate line):
![image](https://user-images.githubusercontent.com/61867589/217329230-59f25b68-c622-4768-9fed-3546ba1f4d34.png)

Since there has been the switch to Vercel: Is this still accurate?

**Comment by oleeskild** [comment]
Nice catch! That is probably confusing for new users. I've removed it in the latest release.
