### ISSUE TITLE
support for customizing favicon

### ISSUE THREAD

**Issue by hxhc** [oleeskild/obsidian-digital-garden#19]
I think the plugin is good enough to use, and so, I pay more attention to the details. 

The favicon of the current pages is the default one. You can see my [page](https://hxhc-notes.netlify.app//) to check out. IMO, this is a little tedious. But I searched the plugin and template repos, and it turned out that both repos don't include any "favicon" codes.

I would thank a lot if you could spare some time to implement a function for customizing the favicon. Thank you for your great work.

**Comment by ThatOtherAndrew** [comment]
You could modify the Nunjucks template code to add your own favicon, which I had a crack at - however I agree, official favicon support would indeed be great.

**Comment by hxhc** [comment]
> 

Thank you for your advice. I tried adding `<link rel="icon"  type="image/jpeg" href="https://tvax4.sinaimg.cn/large/88eff492gy1h0byvoo0f1j208m08mmxg.jpg" />` to the `src/site/_includes/layouts/note.njk` and `/src/site/index.njk` files. But these doesn't work. 

Because I am new to Nunjucks and html, I don't know how to add the proper favicon. Could you figure out clearly where and how to add the favicon? Thank you.

**Comment by oleeskild** [comment]
Will definetely look into this. I'm currently working on a release which would allow you to apply any obsidian theme to your site. I'll try adding favicon support too, as part of that release.

**Comment by hxhc** [comment]
> Will definetely look into this. I'm currently working on a release which would allow you to apply any obsidian theme to your site. I'll try adding favicon support too, as part of that release.

Supporting any Obsidian theme is the most fantastic feature. Masterpiece!

**Comment by oleeskild** [comment]
I've just released a new version of the template and plugin with support for both setting a theme and favicon. Let me know if this is an acceptable solution for your needs @hxhc

**Comment by hxhc** [comment]
It works very well. I appreciate your work and quick responses very much.
