### ISSUE TITLE
Embedded images not showing up

### ISSUE THREAD

**Issue by shisuuu** [oleeskild/obsidian-digital-garden#194]
I've been using this awesome plugin for a while now and never had any problems with it before.
Today after deploying some notes, I noticed that my embedded images ![[image]] weren't showing up.
Instead it shows the images names.

Was there any change after the recent updates?
I'm trying to figure out what could've caused that.

**Comment by shisuuu** [comment]
Ah well, guess I need to read more precisely next time.
Switched over to vercel and everything is working again.

**Comment by oleeskild** [comment]
Nice to hear that it worked out!

Out of curiosity, was there a problem with images when using Netlify? Or was it something else that was wrong?
