### ISSUE TITLE
[Feature Request] DataviewJS support 

### ISSUE THREAD

**Issue by karsonenns** [oleeskild/obsidian-digital-garden#197]
Wondering what it would take to be able to support dataviewJS, either inline queries, or separate files.

**Comment by bppdddqqqq** [comment]
This interests me as well, it's probably that I will be doing the implementation if no one else is up for it.

**Comment by oleeskild** [comment]
Finally got this working! Just released version 2.42.0 of the plugin and it now supports inline dataview, inline dataviewjs and regular dataviewjs 🎉
