### ISSUE TITLE
Feature: comments on pages

### ISSUE THREAD

**Issue by OvrAp3x** [oleeskild/obsidian-digital-garden#199]
I have been looking into implementing some comments feature for the pages.

I have tested with https://giscus.app/ which uses gihub discussions as the backend for the comment field.

configured as such 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/14344702/219622657-db5a2194-e57e-41e1-9c31-78c16012ed6c.png">

Then taking the snippet created from the giscus app and pasting it at the bottom of the .md file and due to the feature of rendering html in digital garden already, this causes the comment field to be loaded and it works great :-)
Example: https://1ar.no/zero-tier-and-github-actions-zero-tier/
source: https://github.com/OvrAp3x/public-brain/blob/main/src/site/notes/ZeroTier%20and%20Github%20Actions%20%E2%80%93%20ZeroTier.md
backend: https://github.com/OvrAp3x/public-brain/discussions

What I am struggling with is how to set it up som that in the settings in obsidian there is a field that the giscus snippet can be pasted in, and automatically appended to the file when it is published.
Any pointers or help about how this can be accomplished?

**Comment by oleeskild** [comment]
Cool! 😄 You could use the newly introduces "slot" mechanism (documented [here](https://dg-docs.ole.dev/advanced/adding-custom-components), which lets you put custom code snippets in various slots in your garden. So if you want this snippet be at the end of every not, excluding you home page, you could add the following file:
`src/site/_includes/components/user/notes/footer/comment.njk`
(The path `src/site/_includes/components/user/notes/footer/` is important here, but the filename itself could be anything, as long as it ends with njk)

Then add your giscus comment script snippet in that file.

This should then put this in the footer of every note automatically. If you want it to also show up on the home page, switch the `notes` part with `common`, like so:
`src/site/_includes/components/user/common/footer/comment.njk`

Let me know if you get it to work!

**Comment by OvrAp3x** [comment]
Great!

I have tested and it works "sort of", The formatting is weird
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/14344702/220075809-e69a3707-488b-4e15-a966-f18aaacbe7d0.png">

The element gets stretched across the whole page, behind the left hand menu bar and other elements. 
(see picture or visit https://1ar.no/concepts/client-isolation/ ) to see 

Any ideas? Im gussing the "boundaries" for the element must be set somehow?

**Comment by oleeskild** [comment]
Ah, sorry, I gave you the wrong slotname. Instead of placing it in src/site/_includes/components/user/notes/footer , it should be placed in src/site/_includes/components/user/notes/afterContent

Then it should be inside the "content container".

**Comment by OvrAp3x** [comment]
Great success!
Thank you very much :-) 

Very useful system, and a lot of options I think (When I learn and understand them! :-P )
