### ISSUE TITLE
[bug] Unable to publish (ipad)

### ISSUE THREAD

**Issue by Mara-Li** [oleeskild/obsidian-digital-garden#2]
Unable to publish a note using obsidian mobile (insider build).
Everything is configured correctly : 
- Repo Key generated
- Github repo : https://github.com/Mara-Li/Mara-Li
- User name : Mara-Li

Is the plugin compatible with mobile ? If not, please change your manifest to set `true` in `isDesktopOnly`

**Comment by oleeskild** [comment]
Thanks for cathing that! I realize I've tested with an old version on mobile.
I used the Buffer.from() to do convert a string to base64. I've now switched to a non-node version. Verified that it worked on iOS. 
Is the latest release working for you as well?

**Comment by Mara-Li** [comment]
Could you please build the manifest and main.js so I can try using BRAT? You could use a github action to automatically build the manifest and main.js file.

**Comment by oleeskild** [comment]
Yup, I've alread updated the main.js and manifest files in the Initial Release here https://github.com/oleeskild/obsidian-digital-garden/releases/tag/1.0.0

**Comment by oleeskild** [comment]
I've also updated the [template](https://github.com/oleeskild/digitalgarden) with some improvements. If you test again, could you try using the latest version?

**Comment by Mara-Li** [comment]
> Yup, I've alread updated the main.js and manifest files in the Initial Release here https://github.com/oleeskild/obsidian-digital-garden/releases/tag/1.0.0

Well, brat detect only change with tag release version, so if you want to beta-test, you need to change this!

I will re-download the plugin to try, but using BRAT is better, so I advice you to change the manifest and release tag!

**Comment by oleeskild** [comment]
Ah, I didn't realize that. I've created a new release with an updated manifest and version number 1.1.0. 
Thanks for letting me know.

**Comment by Mara-Li** [comment]
Everything work as intended!
