### ISSUE TITLE
[Bug] footnotes on Heading will goes wrong

### ISSUE THREAD

**Issue by Zerokei** [oleeskild/obsidian-digital-garden#204]
example:
```
## xxx [^1]
uuuuuu
[^1]: xxxxx
```
and then, the vercel will report: [11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'docId').

**Comment by uroybd** [comment]
This is due to a bug in the upstream footnote rendering library. I've added a PR there, let's see when it gets merged.

**Comment by uroybd** [comment]
Also, added a fix for until the upstream get released.
