### ISSUE TITLE
[Feature request] Support for searching Chinese content

### ISSUE THREAD

**Issue by ouyangzh-CN** [oleeskild/obsidian-digital-garden#219]
#chinese #search

First of all, I'd like to express my appreciation for your work. It's currently the most convenient and efficient way I've found to publish my Obsidian notes. Thank you for your hard work!

However, I noticed that the search function only works with English content. As a bilingual user who frequently writes notes in Chinese, I find it inconvenient that I cannot search for Chinese keywords in my published notes. I believe there are many other users who share the same need.

Therefore, I'd like to request that you consider adding support for searching Chinese content. I believe that this feature would greatly enhance the usability and accessibility of Publish for Chinese-speaking users.

Please let me know if I could help in any form.

**Comment by Jackiexiao** [comment]
I'm not familiar with js, but I think this is because lunr.js does not support searching in Chinese and other languages. Perhaps we can solve the issue of multilingual search (not just Chinese) by using the following library? just my two cents. @oleeskild 

https://github.com/MihaiValentin/lunr-languages/

**Comment by GJRobert** [comment]
Confirmed. UTF-8 characters does not seem to be searchable now :)

**Comment by Lraxer** [comment]
Since the template has replaced lunr.js with FlexSearch.js in oleeskild/digitalgarden#160 (thanks to oleeskild), we can search Chinese contents now. So I think this issue can be closed.

**Comment by ouyangzh-CN** [comment]
Chinese content can be searched now.

**Comment by Crash2333** [comment]
I still can't search Chinese on my site.
Update template to version 1.54.2
Do you need to do anything extra to support Chinese search?

**Comment by GJRobert** [comment]
> I still can't search Chinese on my site. Update template to version 1.54.2 Do you need to do anything extra to support Chinese search? [Crash2333/digitalgarden#29](https://github.com/Crash2333/digitalgarden/pull/29)

If you go to my site http://aiuanyu.vercel.app/ can you search for CJK characters on it?
It seems to work on my sites.

**Comment by Crash2333** [comment]
> > I still can't search Chinese on my site. Update template to version 1.54.2 Do you need to do anything extra to support Chinese search? [Crash2333/digitalgarden#29](https://github.com/Crash2333/digitalgarden/pull/29)
> 
> If you go to my site http://aiuanyu.vercel.app/ can you search for CJK characters on it? It seems to work on my sites.

I just crate PR but not to merge option 
This is my mistake
sorry！！！
