### ISSUE TITLE
[Feature request] support modular CSS layout multi-column 

### ISSUE THREAD

**Issue by juyujeng** [oleeskild/obsidian-digital-garden#222]
please support modular CSS layout: multi-column 
https://efemkay.github.io/obsidian-modular-css-layout/multi-column/

in this CSS, it uses [!multi-column] for multi-column layout
but this CSS class is not recognized as callout class in digital-garden

I found this issue is resulted from the setting in .eleventy.js

would you change this line
`const calloutMeta = /\[!(\w*)\](\+|\-){0,1}(\s?.*)/;`

to 

`const calloutMeta = /\[!([\w-]*)\](\+|\-){0,1}(\s?.*)/;`

**Comment by oyes77** [comment]
in general all features of CSS layout should be supported if they aren't already, just checking them out, and this is aweasome OwO

**Comment by oleeskild** [comment]
Thanks for pointing out exactly what needed to change. I've changed the regex to allow "-" in the latest version of the template.  Also @oyes77 , I've finally added style settings support. You need to update both the plugin and the template for it to work. It's described how to use it here: https://dg-docs.ole.dev/getting-started/04-appearance-settings/#style-settings-plugin
