### ISSUE TITLE
Markdown not converted to HTML on first-line headings in transcluded docs

### ISSUE THREAD

**Issue by philipmorg** [oleeskild/obsidian-digital-garden#23]
If the first line of a transcluded Obsidian note is a heading, then Obsidian Digital Garden seems to render it as "# Heading" rather than as an HTML <h1>.

**Comment by oleeskild** [comment]
Thanks for reporting this. Will push out a fix whenever I find the time :)

**Comment by philipmorg** [comment]
Thank you for making the plugin. I find it very useful.

**Comment by oleeskild** [comment]
Happy to hear that. I've just pushed out version 2.8.4 of the plugin which should fix the formatting issue you're having. Let me know if it's working for you.

**Comment by philipmorg** [comment]
That has fixed it in the several instances I've checked. Thank you!!
