### ISSUE TITLE
ERROR when publish multiple notes

### ISSUE THREAD

**Issue by Eucliddd** [oleeskild/obsidian-digital-garden#231]
[11ty] Original error stack trace: (Repeated output has been truncated…)
--
22:58:45.832 | [11ty]     at TemplateMap.checkForDuplicatePermalinks (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateMap.js:799:13)
22:58:45.832 | [11ty]     at TemplateMap.cache (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateMap.js:484:10)
22:58:45.832 | [11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
22:58:45.832 | [11ty]     at async TemplateWriter._createTemplateMap (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:330:5)
22:58:45.832 | [11ty]     at async TemplateWriter.generateTemplates (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:360:5)
22:58:45.833 | [11ty]     at async TemplateWriter.write (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:407:23)
22:58:45.833 | [11ty]     at async Eleventy.executeBuild (/vercel/path0/node_modules/@11ty/eleventy/src/Eleventy.js:1160:13)
22:58:45.833 | [11ty] Copied 5 files / Wrote 0 files in 0.25 seconds (v2.0.0)
22:58:45.848 | ERROR: "build:eleventy" exited with 1.
22:58:45.866 | Error: Command "npm run build" exited with 1
22:58:46.519 | BUILD_FAILED: Command "npm run build" exited with 1

**Comment by codyburleson** [comment]
I get the same error from the Vercel build when attempting to publish notes:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
--
13:02:27.718 | [11ty] Output conflict: multiple input files are writing to `dist/index.html`. Use distinct `permalink` values to resolve this conflict.
13:02:27.718 | [11ty]   1. ./src/site/notes/3 Resources/Software Applications/HCL Digital Experience/WCM/WCM Java API/WCM Java API.md
13:02:27.718 | [11ty]   2. ./src/site/notes/Home.md (via DuplicatePermalinkOutputError)
13:02:27.719 | [11ty]
13:02:27.719 | [11ty] Original error stack trace: (Repeated output has been truncated…)
13:02:27.719 | [11ty]     at TemplateMap.checkForDuplicatePermalinks (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateMap.js:799:13)
13:02:27.719 | [11ty]     at TemplateMap.cache (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateMap.js:484:10)
13:02:27.719 | [11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
13:02:27.719 | [11ty]     at async TemplateWriter._createTemplateMap (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:330:5)
13:02:27.719 | [11ty]     at async TemplateWriter.generateTemplates (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:360:5)
13:02:27.719 | [11ty]     at async TemplateWriter.write (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:407:23)
13:02:27.720 | [11ty]     at async Eleventy.executeBuild (/vercel/path0/node_modules/@11ty/eleventy/src/Eleventy.js:1160:13)
13:02:27.720 | [11ty] Copied 5 files / Wrote 0 files in 0.18 seconds (v2.0.0)
13:02:27.744 | ERROR: "build:eleventy" exited with 1.
13:02:27.765 | Error: Command "npm run build" exited with 1
13:02:28.495 | Deployment completed
13:02:28.074 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

**Comment by codyburleson** [comment]
I found a solution on my end. For me, this was caused because I had more than one document that specified `dg-home: true` in the frontmatter. Once I ensured that one and only one document had that in the frontmatter, the build started working again. @Eucliddd, can you confirm if this solution also works for you so this issue could maybe be closed?
