### ISSUE TITLE
Oldest note be home note

### ISSUE THREAD

**Issue by oyes77** [oleeskild/obsidian-digital-garden#247]
Basically for troubleshoot reasons, but it would be good to have a home note by defeaut, it either can be a defeaut site in the digital garden that still lets you see other published notes via file tree, or search for stuff, or if the code doesn't allow that (idk) the oldest note in the repo gets the home role.

**Comment by David7ce** [comment]
----
dg-home: true 
---

At the beginning of one note, and you have to put manually.

**Comment by dayne** [comment]
@oyes77 Seems this has been resolved by David7ce's note to use `dg-home: true` flag and this issue could be closed.

**Comment by oleeskild** [comment]
Thank @dayne Closing this
