### ISSUE TITLE
Update custom styling in documentation

### ISSUE THREAD

**Issue by oyes77** [oleeskild/obsidian-digital-garden#248]
https://dg-docs.ole.dev/advanced/tips-and-tricks/

![image](https://user-images.githubusercontent.com/53545025/226748865-be9c44e7-4f2f-4cf5-9904-be9c3b2664c5.png)

**Comment by oleeskild** [comment]
Good catch! I've removed it from the docs. Not really relevant anymore with the current feature set.

**Comment by ingvald** [comment]
i actually needed this today, as i wanted to have backlings enabled on all but the home page, and couldn't get custom style for just index to work as components ref https://dg-docs.ole.dev/advanced/adding-custom-components/
