### ISSUE TITLE
Adapt README regarding Dataview js

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#249]
I think one of the latest releases added DataviewJS support. So I would assume this list in the README needs to be adapted.

![Screenshot_2023-03-22-18-07-48-014_com.github.android~2.jpg](https://user-images.githubusercontent.com/61867589/226967434-cd6b3fab-dc75-4574-a1a4-c05934f19429.jpg)

**Comment by oleeskild** [comment]
Thanks, good catch! Fixed
