### ISSUE TITLE
[bug] codeblocks do not render "[[ ... ]]" properly

### ISSUE THREAD

**Issue by meleu** [oleeskild/obsidian-digital-garden#25]
This is probably some logic related to parsing [[wikilinks]]...

This code block:
```bash
[[ -f "${yamlFile}" ]] && echo 'do something'
```
Results in this:
![image](https://user-images.githubusercontent.com/8508804/161761275-2e9824de-f3ad-4141-91dd-7957fcaf94ce.png)

---

btw: congratulations for creating a tool so well integrated with Obsidian! It's very impressive!! :heart:

**Comment by oleeskild** [comment]
Thank you for the kind words! 😄 

Nice catch! I've pushed a fix which should solve this issue for most cases. Thanks for reporting it.

You'll need to update both the template and the plugin itself as I needed to change stuff in both places for this to work. You should be able to update your template by going to the Digital Garden settings -> Manage site template -> Create PR. Let me know if this fixed your issue.

**Comment by meleu** [comment]
> You should be able to update your template by going to the Digital Garden settings -> Manage site template -> Create PR.

dude! this very feature to update the template is insanely cool!

and yeah, you solved the issue:
![image](https://user-images.githubusercontent.com/8508804/161860525-20d0c632-1529-4b9f-a30b-80dff5a2614a.png)

I really hope that by reading this you put a smile on your face and feel that warmth wee feel when we make a random person on the internet really happy!

:heart:
