### ISSUE TITLE
[feature request] option to setup a dir where all notes are to be published

### ISSUE THREAD

**Issue by meleu** [oleeskild/obsidian-digital-garden#26]
It would be handy to have a way to setup a directory where all notes inside it (and in its subdirs) are meant to be published.

The first thought I had was "having a directory where every note has `dg-publish: true`", but maybe the maintainer has a better idea to implement this.

**Comment by meleu** [comment]
As a workaround, I've created this script: https://gist.github.com/meleu/f9667e76a2744d46686702edeb3cc77c

Requirement: the vault itself must be a git repository (what I usally do).

The script adds a `dg-publish: true` to all versioned `*.md` files that don't have a `dg-publish: ` defined in it's frontmatter.

Consequences of this:

- non versioned files won't be affected (e.g.: gitignored files)
- files without any frontmatter will have one with `dg-publish: true`
- files with a `dg-publish: ` (any value) in its frontmatter won't be touched


While the feature requested in the OP is not implemented, I'll be using that script as pre-commit git hook.

**Comment by oleeskild** [comment]
Thanks for providing a workaround. Hopefully it will serve as a solution for people until this is properly supported.

I'm thinking that this could be implemented by creating a GUI presenting you with the filetree of your vault which would allow you to select folders and/or notes and marking them all with dg-publish: true with the press of a button. Also, the notes already marked with dg-publish, should already be selected. 

What do you think? Would that work for your usecase, or did you have something different in mind?

**Comment by meleu** [comment]
Yeah, that would surely be cool (choose specific directories in a filetree).

However, my first thought was something as simple as what we have in Settings > Files & Links > Default location for new notes:
![choose-dir](https://user-images.githubusercontent.com/8508804/161857568-7bce72d4-9c09-45d1-a758-72bf3d38cb7f.gif)

It could be something like "**Default location for public notes**", and then every note inside that location (subdirs included) would be automatically published, except the notes with an explicit `dg-publish: false`.

**Comment by dclausen01** [comment]
This feature would be awesome, would make my life easier ;)

**Comment by vanadium23** [comment]
You can use Templater with option to create an empty note with enabled frontmatter.

![image](https://user-images.githubusercontent.com/2872741/166160599-abf4c4c5-a9ee-418a-b676-cead014633b7.png)

**Comment by dclausen01** [comment]
> You can use Templater with option to create an empty note with enabled frontmatter.
> 
> ![image](https://user-images.githubusercontent.com/2872741/166160599-abf4c4c5-a9ee-418a-b676-cead014633b7.png)

This dies the trick for me, thanks! Now Obsidian + Digital Garden is everything I need for making and presenting stuff to my students 👍

**Comment by oleeskild** [comment]
That's such a cool workflow. Thank you so much for sharing this tip. I wasn't to keen on making a setting where you define a folder that did not have the publish flag, as I think it would be confusing for a lot of users. All published notes should have a flag. This solution fixes that problem. 

I hope it's okay that I add this tip in the readme? It needs a bit of cleaning up and I think adding this worfklow would be helpful for a lot of people.

**Comment by vanadium23** [comment]
Yeah, I think it can be add as a tip :)

**Comment by meleu** [comment]
Although the Templater seems to be a really handy way to start creating notes that will be public, I think it doesn't fully address the feature request.

Example: if I have a directory with subdirectories and full of hundreds of notes. If I understoo correctly Templater is not able to go into each one of the notes and add the `dg-publish: true` in the frontmatter.

Anyways, the solution we've found so far (the [shell script] and the Templater plugin) is ok for my current workflow. So, yeah, I also consider this issue as "closed.

Thanks guys! :)

**Comment by oleeskild** [comment]
I am working on a release which will make it alot easier to manage and apply the dg-publish attribute to many notes at a time. Hopefully these two features combined will solve your problem. I'll let you know when the release becomes available

**Comment by sharpsteelsoftware** [comment]
Great work on this project @oleeskild ! Do you have any updates on applying dg-publish so we can publish an entire subdirectory of notes with a single property? I am looking for a way to 1. Publish all my notes existing 2. Publish all notes in a subdirectory
