### ISSUE TITLE
Dataview Inline crashing my site

### ISSUE THREAD

**Issue by jeansordes** [oleeskild/obsidian-digital-garden#262]
Hi, I tried updating everything I could … but the dataview inline queries triggers an error :/

The setup is as follow

```
// home.md
`= [[note]].summary`
```

```
// note.md
[summary:: this note is about foo]
```

And the error I get is the following

```
Unable to render inline dataview query.
Please update the dataview plugin to the latest version.
```

**Comment by JackLawhorn** [comment]
Just tried the Digital Garden plugin for the first time and would definitely appreciate a fix to this. I use inline Dataview queries on nearly every note I create, so this isn't really a viable option to me in its current state.

Like @jeansordes my Dataview plugin, as well as my Digital Garden plugin, are completely up to date.

At least some notes with inline queries are still published to my DG, but with the following errors:
- The URLs to those notes aren't formatted (i.e. not slugified) correctly so links to them do not work. They appear to still be accessible via the search bar, but its hard to verify all this without being able to navigate around.
- The content of these notes are cut short where the inline query begins. Elsewhere, all that renders of the note content is a Dataview TABLE query which is at the very bottom of the note. There seems to be some backticks missing in what does render so maybe that has something to do with the source of the issue? Screenshot below:

![image](https://user-images.githubusercontent.com/29128781/231573652-6055f318-1594-4ba5-b3ce-b71fd39613fd.png)

**Comment by signorsarsi** [comment]
I have the same  problem of > [jeansordes](/jeansordes)  with the same error: "Unable to render inline dataview query.
Please update the dataview plugin to the latest version."

Nevertheless I have the last version of the plugin.

**Comment by julesvirallinen** [comment]
Can you provide steps to reproduce this problem? I think it might not be hard to fix

**Comment by julesvirallinen** [comment]
Good news :D 

Turns out this was a whitespace issue in compiler, let's see if this fixes it! 

https://github.com/oleeskild/obsidian-digital-garden/pull/449/files#diff-82551739cf61e2b6a7ae0da93af897cda9d610e30b0d875f3a34531abbda3b14R282

**Comment by julesvirallinen** [comment]
Once this is fixed i'll see if we can address the other issues here!
