### ISSUE TITLE
Inline Dataview JS does not work

### ISSUE THREAD

**Issue by davidkopp** [oleeskild/obsidian-digital-garden#267]
Result of inline Dataview JS queries don't get published.

Example:
```markdown
Total number of notes: `$=dv.pages().length`
```

Result:

```html
<p>Total number of notes:</p>
```

Reference: [Documentation of Inline Dataview JS](https://blacksmithgu.github.io/obsidian-dataview/queries/dql-js-inline/#inline-dataview-js).

**Comment by davidkopp** [comment]
Fixed in [release 2.51](https://github.com/oleeskild/obsidian-digital-garden/releases/tag/2.51.0)

**Comment by neoromantic** [comment]
not sure if that's something on my end, but this won't render:

```
`$= "![]("+dv.current().poster+")"`
```

**Comment by neoromantic** [comment]
@davidkopp

**Comment by davidkopp** [comment]
@neoromantic This is not an issue with the Obsidian Garden Plugin but with the Dataview plugin.
See issue https://github.com/blacksmithgu/obsidian-dataview/issues/1051

**Comment by neoromantic** [comment]
But dataview renders it in my obsidian?

**Comment by davidkopp** [comment]
In my tests it doesn't work in Obsidian. How is the property `poster` defined?
