### ISSUE TITLE
Suggestion: Streamline plugin UI to improve readability [Improvement]

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#268]
### Idea description

Over the last few updates the Digital Garden plugin has received substantial, new functionality, e.g.:

* Path rewrite rules
* Timestamps
* Icons

Having new features in the plugin is of course great.
Yet, at least for me the plugin UI has become somewhat hard to read/understand.

**Therefore, I'd like to make the humble suggestion to think about streamlining the UI for the sake of improved readability.**

---

### Current design

Just as examples, two screens of the current UI:

**🖥 Screen 1: Home screen**

Currently the app has a huge number of editable fields right on the first plugin page:

![image](https://user-images.githubusercontent.com/61867589/230785950-3b57850d-bcec-44da-95d7-681b8e920a49.png)

**🖥 Screen 2: Appearance Settings**

Also the "Appearance Settings" are a sight to behold:

![image](https://user-images.githubusercontent.com/61867589/230785987-0cf2d37a-7b0c-43ed-8546-1e74204ee265.png)

These two screens should just serve as examples, also other screens/dialogs should be reviewed!

---

### Suggestions

**💡 Suggestion 1: Think about having subsections**

Adding headings could improve readbility.
One can refer to the UI of the "Obsidian Git" plugin.

![image](https://user-images.githubusercontent.com/61867589/230786235-49657649-a443-4bc3-b901-b1950f7cd193.png)

![image](https://user-images.githubusercontent.com/61867589/230786402-3303ad0d-91c3-460e-94ae-a1ee00699aff.png)

**💡 Suggestion 2: Split into "basic" and "extended" functionality**

Basic functionality would be:

* Github repo name, username and token
* Base URL
* Appearance
* Slugify
* Manage site template

Extended functionality would be:

* Path rewrite rules
* Note settings
* Timestamps
* Note icons

**💡 Suggestion 3: Add icons to important sections/headings**

Adding icons could improve readbility.
One can refer to the UI of the "Various Complements" plugin.

![image](https://user-images.githubusercontent.com/61867589/230786385-02a1d551-4925-4f0a-9410-c13fd2a2a2be.png)

**Comment by oleeskild** [comment]
I agree, the UI has gotten to complicated with the latest updates, and is not very user friendly. Thanks for making such a comprehensive list of suggestions. I will look through it some time this week 🙌

**Comment by oleeskild** [comment]
I've just released a new version of the plugin which implements a lot of your suggestions. Thanks for making them. Let me know if you find anything else that can be improved to increase user friendliness 😄

**Comment by oleeskild** [comment]
Thanks for the feedback! I agree. Theres way to much going on there. I think it would be good to split it up in multiple sections, each with its own modal, under the appearance header. I'll reopen the issue until I've created a modal for each subsection.
