### ISSUE TITLE
[feature request] RSS feed

### ISSUE THREAD

**Issue by philipmorg** [oleeskild/obsidian-digital-garden#27]
This is very much a "wishlist" feature request, but it would be useful for Digital Garden notes to have an RSS feed, so interested parties can get updates to the garden. I realize something like this brings up related questions, like: does the RSS feed automatically show subscribers updates to notes, and should it do so even if those updates are truly minor (like correcting a small typo). Or should note YAML control this, etc?

Anyway, just wanted to suggest RSS feeds as a feature.

**Comment by oleeskild** [comment]
Good suggestion, an RSS feed would be a nice feature to have. It would be trivial to just add it with some default settings, but I think it should be something you would opt in to in the settings, allowing you to set some parameters like the link etc. I'll look into it whenever I find the time :)

**Comment by stories-with-dice** [comment]
Hey! Any update on this feature?

**Comment by oleeskild** [comment]
@stories-with-dice No, not yet. I've just started looking into it a bit. It's easy to create a rss feed, but i'm not sure how to deal with showing what files are new and updated. Currently there isn't any easy way to get that information when publishing new notes. I might need to either use some GitHub APIs to check each file's history. Not quite sure yet. Any suggestions on an easy way to achieve this would be appreciated 😄

**Comment by stories-with-dice** [comment]
Hm not sure. Can't you re-create the rss xml on every build to get the timestamp of the creation of files?

**Comment by oleeskild** [comment]
I've just released version 1.46.0 of the template, which adds support for Atom/RSS feed. Details on how it works can be read here: https://dg-docs.ole.dev/features/#atom-rss-feed
