### ISSUE TITLE
Applying style settings doesn't work for all themes

### ISSUE THREAD

**Issue by sanderdatema** [oleeskild/obsidian-digital-garden#281]
The Style Settings plugin doesn't work for all themes. For example, when applying settings for the PLN or Blue Topaz theme, nothing is added to the git repo, it's just an empty commit.

**Comment by GJRobert** [comment]
My experience: switch to `PLN` **on Obsidian first**, and then push Style Settings of `PLN` onto Digital Garden (you can then switch to other themes on Obsidian afterwards);

for Style Settings of `Blue Topaz` onto Digital Garden, switch to `Blue Topaz` **on Obsidian first**.

**Comment by oleeskild** [comment]
I've just released a new version of the plugin and the template which _should_ fix the issues you all are experiencing. Try updating them both, and then click the "Apply style settings" button again. 
Please let me know if it works as you expect now, or if there are stille some issues.
