### ISSUE TITLE
Is there a way to exclude portion of a note from being published?

### ISSUE THREAD

**Issue by giocoal** [oleeskild/obsidian-digital-garden#302]
Hi! First of all, thank you for this incredible extension, so useful and easy to use.

My question is: is there a way to exclude portion of a note from being published?

**Comment by shinanqu** [comment]
I also thought about such a feature. Often I want to add private information to a note that isn't meant to be published. Currently, I just refrain from doing so. Such an option would be very useful.

**Comment by K1ngP3ach** [comment]
This is exactly what I would like to know as well! I am planning a D&D campaign and would like to use the DG as an in-game reference encyclopedia and would like to reveal information as my players learn new things/talk to NPCs. It would be nice to have some kind of bracketing to use in the note that would skip over or hide the information from being published to the DG.

**Comment by zcysxy** [comment]
I am implementing a custom filter, which allow users to specify custom syntax to hide or replace text within a note. For example, I am using pandoc-compatible syntax:

```markdown
::: hidden
Private information that should not be written to the remote repository.
:::
```

This will also close #77

**Comment by oleeskild** [comment]
Thanks to @zcysxy, the latest release of the plugin now supports replacing arbitrary regex expressions before publishing which should allow you to automatically hide certain parts of the note before publishing. 🎉 

Also, another way to do this is using [obsidian comments](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Comments). These will be stripped away from the note before publishing.
