### ISSUE TITLE
Changing theme in Obsidian does not take effect

### ISSUE THREAD

**Issue by mauricioabreu** [oleeskild/obsidian-digital-garden#306]
First, thank you for the amazing project.
I've recently set up a digital garen using the plugin: https://samambaia-umber.vercel.app/

When I set the theme do `Default` using the menu `Appearance -> Manage Appearance`, should it be similar to the Digital Garden docs? (https://dg-docs.ole.dev/)

What am I missing? I can see that I don't have a CSS file starting with `_theme`. Should I have it? How?

**Comment by oleeskild** [comment]
It's probably badly named. The default theme is not applying anything to the site, and results in the site just using the default styling. Which is how the garden looked originally when I first made this project. After implementing support for community themes I haven't bothered putting much effort into the default styling, as I assume most people will use a community theme anyway. 

The docs uses the "Red Graphite" theme, with the dark base theme. Selecting that should give you a look that's similar to the docs 😄

**Comment by rokville** [comment]
(Sort of related) Is there a place to see examples of all the theme options?  There are so many (which is amazing) but unless I am missing something, I have to apply each one and publish it to see what it looks like.

**Comment by mauricioabreu** [comment]
@oleeskild my bad, sorry. It is now working fine.

**Comment by oleeskild** [comment]
@rokville unfortunately publishing it is the only way to see the change. But it is the same themes as those available for obsidian itself. So browsing the themes using the default obsidian "theme store" should give you an idea of how they look.

**Comment by rokville** [comment]
oh, that's great! I didn't realize they were matched with the ones in the app.  Thank you.  Also, thank you for this great plugin!!!
