### ISSUE TITLE
Search functionality is flawed

### ISSUE THREAD

**Issue by Stelvey** [oleeskild/obsidian-digital-garden#307]
If I've got a word like "handshake" in one of my .md files (let's say example.md) - the search only finds it if you don't write it whole.
For example:
hand: search finds example.md
shake: search doesn't find example.md
handshake: search doesn't find example.md

**Comment by oleeskild** [comment]
Yup, it has been an underwhelming search experience. I recently switched the "search engine" from lunr.js to FlexSearch, in addition to switching the search logic from serverside to clientside. Try updating the template to the latest version. You should see a _significant_ improvement in both speed and accuracy. Let me know if works as you expected after the update.

**Comment by Stelvey** [comment]
The problem I wrote about no longer occurs, thank you!
