### ISSUE TITLE
Unable to publish

### ISSUE THREAD

**Issue by froses** [oleeskild/obsidian-digital-garden#309]
Hello, 

I'm trying to deploy a simple note to my garden, but nothing happens when I use "Publish a single note". The message "Publishing note..." is displayed and no error message appears. So, I think the note has been published, but when I visit the Vercel site, a page with a "Nothing here message" appears. The unique note in my vault haves a, I think, a valid frontmatter with "dg-home: true" and "dg-publish: true". It seems the GitHub repository is OK and Vercel deployed correctly your site template.

But when I access the plug in configuration, and I try, for instance, the Base URL value, the message: "Failed to update settings. Make sure you have an Internet connections" is displayed. And yes, I have an Internet connection active.

I installed the plugin two hours ago, so I have the latest version. 

I use the URL: https://froses-digital-garden.vercel.app to access to my garden.

What I'm doing wrong?

Thanks in advance, 

FRA
![NothingHere](https://github.com/oleeskild/obsidian-digital-garden/assets/8214985/49b13de5-c695-4612-b4b2-ec2d42ecd18e)

**Comment by shinanqu** [comment]
"It seems the GitHub repository is OK and Vercel deployed correctly your site template."

Everything seems ok, but still, you get an error message when you make any changes in the settings? I never had such an error message in the settings, so something is faulty with the installment, I assume. Can you figure out what it is? The GitHub Authentication is correct? There shouldn't be any error message, when you change the settings or change the base URL.

Just to be sure... Do you have any other frontmatter? Can you create a test note and create a parmalink:
dg-permalink: test

**Comment by froses** [comment]
Hi,

I attach you my original note. I have only one frontmater.

I’ll create a test note with this frontmatter and I’ll try to deploy it:
---
dg-home: true
dg-publish: true
dg-permalink: test
—

Thanks!

FRA
￼

**Comment by froses** [comment]
Done! I created a test note and I tried to publish it, but nothing happened.

I attach my test note.

Thank you so much for your prompt response!

FRA

￼

**Comment by shinanqu** [comment]
Sorry, I overlooked that when you have the home tag, the permalink is probably ignored. Thus you can try:

---
dg-publish: true
dg-permalink: test
---

And then the note should be at
https://froses-digital-garden.vercel.app/test

but there seems to be a different problem.
Git Repo Name, Git Username and Git Token are all correct? Can you double and triple check?

**Comment by froses** [comment]
Hi, 

I tried with the new frontmatter, but the problem persists. I use the 

I attach my note and a couple of screenshots: the list of projects in GitHub (froses/froses_digital_garden) and the Digital Garden Settings. The GitHat user is ***@***.*** ***@***.***> and the token is OK. I use the same token with the Obsidian Git Plugin without problems. And my Git credentials are cached on my computer (I executed "git config --global credential.helper store» a couple of years ago) so, may be the Digital Garden Plugin can use those Git credentials.

Regards, 

FRA

￼￼￼

**Comment by shinanqu** [comment]
"may be the Digital Garden Plugin can use those Git credentials."

Yes, maybe... Maybe not... Who knows... There must be some kind of issue. I can only randomly guess. If it doesn't work, there must be a reason. I would try to do everything from the beginning, install everything again, perhaps with new credentials, perhaps with a new token, perhaps with a new account, etc. etc. etc. Of course, it makes sense to say at all steps "it should" and I agree that it should. But it doesn't.
Perhaps somebody else can help a bit more... Sorry that I couldn't solve the issue. I wish you good luck to get it running!

**Comment by AgedLace** [comment]
I've spent the entire day working on this and I'm having the exact same problem as the original poster.  I've checked, double-checked, triple-checked the settings, the token ... I've even tried putting the files in different places in the vault ... in  the root dir, in /src and in /src/site/note [which I thought was generated by the plugin scripts?], but none of these options works.  It's too bad because this is the best setup I've seen, and would like to use it, but after wasting untold hours today, I'm having to move on to something else.  Thanks anyway!

**Comment by froses** [comment]
Hello, 

I created a new Vercel project with a new GitHub repository, and it seems all is working.

On the plug in configuration, I entered de GitHub repository name without prefix. So, I use MyGarden instead of froses/MyGarden.

I tested the plug in on a vault without Obsidian Git plug in installed.

Regards, 

FRA

**Comment by shinanqu** [comment]
I am glad you could find a solution!
The Digital Garden is working well, so just installing everything from scratch should always do the trick. 
Good luck with your Digital Garden!
