### ISSUE TITLE
The "add publish flag" command sometimes creates invalid yaml

### ISSUE THREAD

**Issue by AstronosMK** [oleeskild/obsidian-digital-garden#315]
When using the add publish flag the yaml of some of my files becomes invaild
This happens when there are some special characters in the alias

for example :

```
---
alias: ["Langchain: PDF Chat App (GUI) Step-by-Step Tutorial"]
---
```

becomes

```
---
alias: Langchain: PDF Chat App (GUI)  Step-by-Step Tutorial
dg-publish: true
---
```

due to the quotes and brackets getting removed it becomes invalid

**Comment by SteveJohnSteele** [comment]
2024 and this is still an issue 
tags: 
  - abc 
  - xyz 
 becomes 
 tags: abc,xyz 
 
 Also data with "" in it get the "" stripped out, making a total mess. 
 
 Please leave existing data alone
