### ISSUE TITLE
Make raw URL links clickable

### ISSUE THREAD

**Issue by davidkopp** [oleeskild/obsidian-digital-garden#317]
I have many URL links in my Obsidian vault that are just raw text and not well-formed Markdown links in the format `[text](link)`. That is not a problem inside Obsidian, because the links are clickable there. However, when they get published, the raw links inside the HTML pages are not clickable.
It would be great, if this plugin could convert raw links into clickable links. Example:
`http://example.com/` → `[http://example.com/](http://example.com/)`

My current workaround:
Using custom filters (#304) to replace the raw links with valid Markdown links.
Regex pattern: `([^(\[]|\n)(https?:\/\/.+)`
Replacement: `$1[$2]($2)`

**Comment by andrey-jef** [comment]
I also upvote this feature request. 

My current workaround:
- manually put the url into <>, that is: `<url>`
- or use plugin Linter in Obsidian with enabled rule to automatically put the url into <>

**Comment by HistoryInvestor** [comment]
Hi all - apologies for bringing back up an old topic - but is there any way to disable this feature on a user's end? @oleeskild 

I am using this for a linguistics-related site, and thus I use a standard linguistic method of writing sounds and syllables. The standard break for a syllable is a full stop (.)...

So, all my notes now have fake external urls that go nowhere, but also break up the words by putting external link emojis inside of words. For example..., "gi.ge.al" and "va.pa" are showing up as urls. 

Thank you!

**Comment by oleeskild** [comment]
@HistoryInvestor This is controlled by a library called markdown-it. To turn this off you can modify your settings like this: 
1. Go to your site in github and navigate to `src/helpers/userSetups.js`
2. Click the edit button

![Image](https://github.com/user-attachments/assets/1480bef1-b781-43bb-851a-c1bc26a4799b)

3. Add this line `md.options.linkify = false;` as in this image, and commit the changes. 

![Image](https://github.com/user-attachments/assets/fa6a1a36-8d53-4209-b03a-479de34cfe6d)

Vercel should pick up your changes, and in about a minute it should be fixed on your site. Let me know if you make it work or not.

**Comment by HistoryInvestor** [comment]
@oleeskild - that was amazingly easy and my apologies for not being super tech savvy here. I appreciate you taking the time to take the screen shots. I will keep recommending this approach to using Obsidian. 

I am using Cloudflare to pull things, and it worked immediately. Thank you again!
