### ISSUE TITLE
[minor] empty favicon commit when updating updating Appearance Settings

### ISSUE THREAD

**Issue by meleu** [oleeskild/obsidian-digital-garden#32]
Not a biggy...

When I update the theme without changing the favicon, the plugin creates an empty commit for the favicon.

The maintainer already replied about this topic here: https://github.com/oleeskild/obsidian-digital-garden/issues/29#issuecomment-1092056953

I'm opening this issue just to help to remember.

**Comment by oleeskild** [comment]
This has been fixed in the latest release, 2.9.1.
