### ISSUE TITLE
Missing Navigation bar…

### ISSUE THREAD

**Issue by DudeThatsErin** [oleeskild/obsidian-digital-garden#321]
I have set up this plugin and for some reason my navigation bar is missing. Not sure what I did or how to fix it.
Please help!

https://blog.dudethatserin.com is the site.
I am missing the left sidebar or the 3 lines on mobile.

**Comment by Tu-Zhenzhao** [comment]
Hi I am similar request, how do you set navigation bar in .md file? I cannot find a good way to make it
