### ISSUE TITLE
Feature Request: Allow all front matter to pass through to Eleventy

### ISSUE THREAD

**Issue by gmuller** [oleeskild/obsidian-digital-garden#33]
It would be good if we could allow all front matter to pass through to the templatng system, that way you could use things like dates and last mod times in templates to show update time periods, or any other arbitrary front matter. You could probably also take advantage of collections in eleventy and tags in obsidian. Simply allowing whatever front matter that exists in obsidian to pass through is a good first step though.

**Comment by oleeskild** [comment]
That would be nice! The plugin actually did this some versions ago. However you get into problems when using formats 11ty don't understand. See [this issue](https://github.com/oleeskild/obsidian-digital-garden/issues/18)

But it would be nice to offer this as an opt-in. Perhaps as a global default setting for all notes to let all frontmatter through, while also allowing you to override this with a frontmatter flag in specific notes.

What do you think? Do you have any input on how best to solve this?

**Comment by oleeskild** [comment]
@gmuller I've added this as a setting in the new "Note settings" view which you can find in Settings>Digital Garden>Note Settings>Edit. If you enable the "Let all frontmatter through", it will be enabled globally. You can also specify the setting on a per-note basis, setting dg-pass-frontmatter to true or false. Let me know if it's working as you expected.

**Comment by gmuller** [comment]
I'm testing this now, so far so good. I wanted to include some small things like lastmodified date, and the ability to use collections more extensively. I will report back on any "gotchas" I encounter

You've done some great work here, this is turning out to be a really easy way to manage a full site, not just something like a digital garden. Maybe a bit out of scope, but including functionality like this really expands what you can do with the plugin and with Obsidian.

**Comment by Calorion** [comment]
Forgive me for asking, but—what's Eleventy?

**Comment by oleeskild** [comment]
Eleventy is a static site generator, and is the "engine" being used by the [digital garden template](https://github.com/oleeskild/digitalgarden) to generate your site from the obsidian markdown files. Here's a link: [11ty.dev](https://11ty.dev)
