### ISSUE TITLE
Having ${{ something }} in codeblocks makes things after $ disapear

### ISSUE THREAD

**Issue by MTRNord** [oleeskild/obsidian-digital-garden#332]
It seems like something is preprocessing the `{{ something }}` away. I assume mathjax. However, escaping does stop this but also shows the backslashes, meaning `${{ something }}` becomes either `$` or `$\{\{ something \}\}` if escaping.

This did hit me when trying to have a github action manifest in a note. This is rendered properly in obsidian.

**Comment by oleeskild** [comment]
This has now been fixed in the latest version of the template. [Update the template](https://dg-docs.ole.dev/getting-started/06-updating-the-template/) and text like {{ something }} should no longer be an issue.
