### ISSUE TITLE
Partial theme/CSS support? (ITS)

### ISSUE THREAD

**Issue by rodrigoportela** [oleeskild/obsidian-digital-garden#340]
I'm testing Digital Garden with the ITS Theme (https://github.com/SlRvb/Obsidian--ITS-Theme) and founding two problems with features that seem unsupported:

1.  Alternate color schemes don't seem to work. Apparently, the published site is using the default theme settings for this as if I hadn't changed it with the Style Settings plugin and applied the changes with the option inside Digital Garden settings.
2. Some of the CSS/theme features I tested aren't working on the published site. What they seem to have in common is that they are supposed to work through attributes applied inside the code of a callout or image embed after `|`. Doing it without the attributes works as expected, but when adding them on the published site that line gets published as the code in the case of a callout and as `!` followed by a link with the attribute as its text in the case of an image, instead of being rendered with the attribute having effect in both cases.

**Comment by rodrigoportela** [comment]
Update: I tried adding the CSS file they have on the theme website for Obsidian Publish to the `src/site/styles/user` folder and it gets the file referenced in the published page as expected, but it also doesn't seem to make any change to the mentioned issues.

**Comment by DudeThatsErin** [comment]
I seem to have this issue with minimal. Did you ever solve this @rodrigoportela ?

**Comment by rodrigoportela** [comment]
> I seem to have this issue with minimal. Did you ever solve this @rodrigoportela ?

No, I didn't.

**Comment by oleeskild** [comment]
The `![[image.png|left|200]]` and `> [!infobox|wikipedia]` syntax for images and callout styling has not been supported until recently. If you update to the latest version of **both** the plugin and the template, you should find that they should work as expected. I've been told on the discord that there are still some issues, but I'm looking into it. 

Let me know if it works as expected now, after the update 😄

**Comment by oleeskild** [comment]
In the latest BETA release (can be installed using BRAT), this seems to have been fixed. Will close this when the new version is released.

**Comment by Leiyi548** [comment]
> The `![[image.png|left|200]]` and `> [!infobox|wikipedia]` syntax for images and callout styling has not been supported until recently. If you update to the latest version of **both** the plugin and the template, you should find that they should work as expected. I've been told on the discord that there are still some issues, but I'm looking into it.
> 
> Let me know if it works as expected now, after the update 😄

not useful,This is my website https://hua-dong-sole.vercel.app/religion/.
I update to the latest version of **both** the plugin and the template.
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/76139422/6c503fac-b082-4036-a515-e0f9c10ede40)
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/76139422/2c680029-3084-417f-894e-352e165c6db0)
