### ISSUE TITLE
[Bug] Mobile, again

### ISSUE THREAD

**Issue by Mara-Li** [oleeskild/obsidian-digital-garden#35]
Hello ! 
I try to push using mobile (IOS - Iphone) but nothing seems to work : I have no notice and nothing appear on the github.

Also, I work on a "seems of" fork of your project, using my own solution (obs2mk, a python script used as a Github Actions). You can check it out if you want ! 
https://github.com/Mara-Li/obsidian-mkdocs-publication

This plugin doesn't work too with mobile :(

**Comment by oleeskild** [comment]
Hi!
Hmm, that'sweird. It's working when I'm testing on my iPhone. What version are you on, and what command are you running? 

That's awesome, let me know if you need any help with any of it.

**Comment by Mara-Li** [comment]
I run for all documents.
It's seems to be around the base64 things. Dunno why, but specially on my phone base64 converting text. 
I tryed the V1, where you use `Buffer.from(text).toString('base64')`. This work all good. But not on my app. I think there is maybe something around Obsidian update?

**Comment by oleeskild** [comment]
By v1, do you mean version 1 of the plugin? If so try upgrading to 2.8.5 and see if that helps.

You're right. The Buffer class is actually a node specific module/API. When running on mobile, you obly have access to browser APIs. I switched to using the library js-base64, which also works on mobile. Take a look in the utils.ta class in the repo. If you change the Buffer.from code to something like this, it should probably work on mobile too. Let me know of it solves it or not.

```
import { Base64 } from "js-base64";

function arrayBufferToBase64(buffer: ArrayBuffer) {
	let binary = "";
	const bytes = new Uint8Array(buffer);
	const len = bytes.byteLength;
	for (let i = 0; i < len; i++) {
		binary += String.fromCharCode(bytes[i]);
	}
	return Base64.btoa(binary);
}

```

You can then use it like this:
```
const imagePath = getLinkpath(imageName);
                    const linkedFile = this.metadataCache.getFirstLinkpathDest(imagePath, filePath);
                    const image = await this.vault.readBinary(linkedFile);
                    const imageBase64 = arrayBufferToBase64(image)
```

**Comment by Mara-Li** [comment]
Thanks a lot to investigate my issue !
After some try, using the js-base64 work well, simply using `const contentBase64 = Base64.encode(text).toString();`

Now, I need to understand why your plugin crash on my iphone :(

**Comment by Mara-Li** [comment]
No, nothing appear in Notice nor in my Github repo...
I use the last version for the repo template and the plugin. Everything is correctly configured (because my PR worked)

**Comment by Mara-Li** [comment]
Also, my config : 
- IPhone 12 
- IOS 15.4.1
- Obsidian mobile 1.2.1

**Comment by oleeskild** [comment]
Hey,
Many updates have been released since this bug was posted. I've not been able to reproduce it. Are you still having issues on mobile or has it resolved itself?

**Comment by Mara-Li** [comment]
As I made my own plugin and no longer your, I close this issue.
