### ISSUE TITLE
Feature request: "toggle publish tag" command

### ISSUE THREAD

**Issue by inputsh** [oleeskild/obsidian-digital-garden#351]
There's currently `Add publish tag` which will add `dg-publish: true` but once that's added to a file there's no way of removing it via a command.

**Proposal:** `Toggle publish tag`

I'd like to be able to configure a keyboard shortcut that will publish *and unpublish* a note:

- If `dg-publish` exists and is set to true, remove it (or set it to false?)
- If `dg-publish` doesn't exist, add it and set it to true.

Currently I have to manually navigate to the top of the file to remove it, which feels a bit inconvenient from time to time.

**Comment by julesvirallinen** [comment]
would it make sense if add publish tag toggled? I'm wondering if changing the action is a breaking change
