### ISSUE TITLE
Low image resolution on website, but high image resolution in GitHub

### ISSUE THREAD

**Issue by quinn-p-mchugh** [oleeskild/obsidian-digital-garden#355]
Hi there,

First off, amazing plugin - thanks for your efforts!

# Issue Summary
I have an image on [this webpage](https://www.garden.quinnmchugh.net/about-the-garden/data-model/) that appears blurry when compared to the [source image uploaded to GitHub](https://github.com/quinn-p-mchugh/digital-garden/blob/main/src/site/img/user/Z00%20Meta/Data%20Model.excalidraw.png).

# Comparison

## [Image on Website](https://www.garden.quinnmchugh.net/about-the-garden/data-model/)
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/40648753/0e446872-827d-42f4-aa3d-50b164f1e0d5)

## [Image Uploaded to GitHub](https://github.com/quinn-p-mchugh/digital-garden/blob/main/src/site/img/user/Z00%20Meta/Data%20Model.excalidraw.png)
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/40648753/3e054b4b-48b0-408a-9f11-f3330a6aeb5c)

# Steps to Reproduce
1. Embed `png` image into note. 
```
---
dg-publish: true
---

Testing PNG Embedding
![[my-image.png]]
```
3. Publish note to GitHub repository using plugin.
4. Build website using Vercel.

**Comment by russellgordon** [comment]
I am certain this is not the recommended solution, but I also ran into this, and was able to work around it by editing the `.eleventy.js` file.

See image below. At left is the original contents of that file. At right are my modifications. I've essentially told eleventy to leave GIF and PNG files alone – to not optimize them. I prefer do that myself before publishing to GitHub through the Digital Garden plugin in Obsidian.

@oleeskild Would you be willing to add a flag in the Digital Garden settings panel in Obsidian to control whether image optimization happens? Or perhaps to control what image formats will be optimized?

<img width="1512" alt="Screenshot 2023-08-15 at 1 27 00 PM" src="https://github.com/oleeskild/obsidian-digital-garden/assets/6400195/212fd4d9-57b3-4a41-b121-f5a3ec4c9153">

The edited file itself on GitHub:

<img width="1624" alt="Screenshot 2023-08-15 at 1 30 00 PM" src="https://github.com/oleeskild/obsidian-digital-garden/assets/6400195/aa4666e7-1769-4482-bdc8-f4c5085ce2c4">
