### ISSUE TITLE
Git API returns 409 if the size of a document is too large

### ISSUE THREAD

**Issue by gmuller** [oleeskild/obsidian-digital-garden#38]
Because the images are base-64 encoded, if you include too many images on a page, you might unintentionally cross the boundary that the GitHub API seems to allow. Here are the errors in the console I got when trying to publish a note that included a lot of pictures:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/132286/164029108-b244d5a1-1834-4e8e-991d-97d569d02683.png">

Not sure what the right fix is for this. Should images be linked instead of encoded? Tough to tell.

**Comment by oleeskild** [comment]
Better late than never: @uroybd recently improved this by instead uploading images separately in to its own folder, and referencing them in the note. This problem should now be solved 🎉
