### ISSUE TITLE
Not quite working to publish correctly, see screenshots

### ISSUE THREAD

**Issue by trijste** [oleeskild/obsidian-digital-garden#39]
Not sure what I'm doing wrong. I can publish the home page, but when I try to link to other pages on the home page, they all resolve to this message:

![Nothing here-Safari-23042022-1230](https://user-images.githubusercontent.com/23725702/164914907-8f9e9537-1a00-4fab-93a4-7b260db8a5f3.png)

And my homepage looks like this, with odd link names I can't seem to control:

![httpstrijste netlify app-Safari-23042022-1232](https://user-images.githubusercontent.com/23725702/164914946-b43421fb-5511-463a-99b6-4bc82f1b3e1b.png)

Have I done something wrong? Is there a way to fix this issue?

Thank you!

**Comment by oleeskild** [comment]
Looking at your repository called digital garden, it seems you haven't updated to the latest version of the template. You can do that by going to obsidian settings > digital garden > manage site template > create pr. You will then be presented with a link after about 20 seconds. Clicking this lets you complete the pull request and merge the latest changes into your repository. 

Let me know of that makes it work or if you need any more help.

**Comment by trijste** [comment]
Thank you, @oleeskild! I knew there was something I was missing or had glossed over. I have followed your notes, and everything is working as expected. Thank you for all the work you've done and continue to do and all the support you provide.
