### ISSUE TITLE
unused image still in site/img/user folder

### ISSUE THREAD

**Issue by jrtx0** [oleeskild/obsidian-digital-garden#391]
when unpublish, unused image still in site/img/user folder.

**Comment by julesvirallinen** [comment]
Could you provide an example or steps to reproduce?

**Comment by jrtx0** [comment]
> Could you provide an example or steps to reproduce?

1. publish a note which include image (e.g. test.jpg) 
2. delete from vault
3. check /img/user folder content, you will notice test.jpg is still there.

**Comment by julesvirallinen** [comment]
Recreation: 

- [Add image](https://github.com/julesvirallinen/testing-garden/commit/f8c4213d76e6d9850a8198bede641e5b01dc9838)
- [remove image](https://github.com/julesvirallinen/testing-garden/commit/e5023aabf35935ec4855d235b67aeda2324ee7a9)

Seems to be there! Thanks for the ticket!
