### ISSUE TITLE
Add testing vault to repository

### ISSUE THREAD

**Issue by julesvirallinen** [oleeskild/obsidian-digital-garden#396]
As this project has a lot of moving parts and specific functionality, I think it would be extremely useful to add a testing vault to the repository. 

It would include most functionality of a normal digital garden, and can be used to locally verify that the plugin is working, and in use in tests. 

It's not recommended to use personal vaults for development anyway, so this could help with overall safety and maintainability.

**Comment by oleeskild** [comment]
That is a very good idea, I agree!

**Comment by julesvirallinen** [comment]
Testing vault is added and works great!
