### ISSUE TITLE
Links in transclusions fail to render

### ISSUE THREAD

**Issue by ThatOtherAndrew** [oleeskild/obsidian-digital-garden#40]
If I have note A which contains a note to `[[abc]]`, then note B which contains a transclusion of note A (`![[A]]`), then the link fails to render as HTML and doesn't become clickable. I'm not entirely sure which versions are affected, however I do recall my links working earlier.

If it's of any use, here's [my notes site](https://notes.thatother.dev/) which demonstrates this issue.

**Comment by oleeskild** [comment]
Right, thanks for reporting this. This was a side effect of me trying to fix that wikilinks inside code blocks shouldn't be rendered as links. I'm working on a fix for this right now.

**Comment by oleeskild** [comment]
I've just released a new version which should fix this issue. Let me know if it works!

**Comment by ThatOtherAndrew** [comment]
It's fixed some of the links, however nested transclusions don't seem to resolve. I'm not entirely sure if this worked before, however support for this would be incredibly useful if possible.

**Comment by oleeskild** [comment]
Great! This has actually never worked. But it's on my todo list. I'll let you know when I've added it.

**Comment by ThatOtherAndrew** [comment]
Alright, thank you very much!

**Comment by oleeskild** [comment]
I've just released a new version of the plugin, 2.10.0, that supports rendering transclusions within transclusions up to 4 levels deep. Let me know if the release fixes your problem.

**Comment by ThatOtherAndrew** [comment]
That's great, thank you! One last little nitpick - is it intended that the titles of nested transclusions don't render?

**Comment by oleeskild** [comment]
No that was not intentional. Any suggestions of what should be there instead? Maybe just a regular link? What do you think?

**Comment by ThatOtherAndrew** [comment]
I'm not entirely sure what would be best - it might be worth asking some others for their opinions, as I personally don't have any significant preference, as long as it's all consistent (which you've done a pretty great job of achieving thus far!).

**Comment by uroybd** [comment]
@ThatOtherAndrew is this still affecting you? I think I've fixed it while working on transclusion.

**Comment by ThatOtherAndrew** [comment]
It appears to be resolved for me, thank you!
