### ISSUE TITLE
[BUG] Sidebar with menus partially open, partially closed

### ISSUE THREAD

**Issue by colabcolibri** [oleeskild/obsidian-digital-garden#403]
I'm having issue with the view of sidebar, with some of the folders open, and other not open, when the site is loaded.
In fact, right now, just one of the folder is folded and the others are open.

Am I missing something? Or it is a sort of bug?

The folder "Raizes" is folded, and the others are open. I would like only the folder with the file in the view, to be open. In this case, the folder "Comece por aqui". And all other be folded, by default. Is it possible to do?
<img width="1822" alt="Captura de Tela 2023-09-16 às 12 28 37" src="https://github.com/oleeskild/obsidian-digital-garden/assets/95150434/2d57ec61-2ab1-4c7e-a943-92f461f57750">

**Comment by dayne** [comment]
I was just testing and this probably isn't a bug but is reflecting how you, in that specific browser you were using on the site, had been doing navigation of your own side bar.

I've tested a couple times as you open the side bar it keeps track of the state of sections/sub-sections you've opened.  You can close/re-open/refresh and it will keep that state.  Open up a new private windows / incognito window and everything will be collapsed again.  

I recommend closing this bug as this is probably expected and wanted behavior:
- start collapsed by default
- remember state so upon return visit (or multiple tabs open) you (the current browser) can readily access the sections you've been visiting.
