### ISSUE TITLE
[Feature request] calculate dataview on publish

### ISSUE THREAD

**Issue by vanadium23** [oleeskild/obsidian-digital-garden#43]
I would like to see same transform as a excalidraw. But currently is not supported by dataview, see https://github.com/blacksmithgu/obsidian-dataview/issues/42.

**Comment by oleeskild** [comment]
I've been trying to implement this, but it's hard to do properly. I've managed to hack something together that is working when the file is open and in preview mode. But it's fragile and would easily break.

Awesome to see that the author of dataview is looking into supporting something like this. I will follow the thread you posted closely. Thanks for letting me know about it.

**Comment by oleeskild** [comment]
Great news @vanadium23. The issue you linked to have recently been resolved and functionality for rendering markdown from a query has been implemented in the Dataview API. I've just release version 2.14.0 of the digital garden plugin which add support for rendering dataview queries.

**Comment by vanadium23** [comment]
Great news!
