### ISSUE TITLE
[BUG] Plugin no longer works on iOS and Android

### ISSUE THREAD

**Issue by stalegjelsten** [oleeskild/obsidian-digital-garden#438]
Version 2.48 and 2.49.1 does not load on iOS or iPadOS with the error message "Failed to load plugin digitalgarden".

**Comment by MahmadSharaf** [comment]
Not even on Android with same error. I have even created a new empty vault to check if my vault not corrupted some how

**Comment by rikrose** [comment]
Tripped over this in  2.51.0 also.

**Comment by oleeskild** [comment]
The latest version, 2.52.0, should make the plugin work on both iOS and Android again. Let me know if updating fixes the issues for you
