### ISSUE TITLE
Style Settings not applying to Garden

### ISSUE THREAD

**Issue by DudeThatsErin** [oleeskild/obsidian-digital-garden#447]
I keep getting a notification that there is nothing to update but my style settings are clearly not applying to my website.

My callouts are supposed to have this border (from minimal theme) and they do not.

Obsidian App:
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/2681022/9ccde94e-0a58-43c1-928a-7950c5fd619d)

Garden:
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/2681022/bdf29b48-33b6-492f-a51d-52253f9a9383)

I have no idea what is going on. I have tried changing the theme on the site and changing it back but it doesn't work. I really like the Obsidian app's look to callouts and my theme in general so I don't understand why it isn't applying.

I tried creating a PR and merging that into my repo but it isn't working.

**Comment by oleeskild** [comment]
What button are you clicking when applying the style settings? This one?

![CleanShot 2023-10-01 at 15 15 50@2x](https://github.com/oleeskild/obsidian-digital-garden/assets/6201338/e4825ea2-23d6-48ca-8f7b-4dd7527e092e)
I realize it's not great UI that it is not the accent color. It will be fixed in the next update of the plugin.

**Comment by julesvirallinen** [comment]
@oleeskild this relates to https://github.com/oleeskild/obsidian-digital-garden/issues/323

It seems that style settings makes some stuff css, and just does MAGIC with the other stuff (maybe themes get the info directly or smth?)

**Comment by DudeThatsErin** [comment]
> What button are you clicking when applying the style settings? This one?
> 
> 
> 
> ![CleanShot 2023-10-01 at 15 15 50@2x](https://github.com/oleeskild/obsidian-digital-garden/assets/6201338/e4825ea2-23d6-48ca-8f7b-4dd7527e092e)
> 
> I realize it's not great UI that the button is not the accent color. It will be fixed in the next update of the plugin. 

yes this button

**Comment by cyanomys** [comment]
I am also having this problem fwiw. Clicking the right button and everything.

**Comment by oleeskild** [comment]
I've just released a new version of the plugin and the template which _should_ fix the issues you all are experiencing. Try updating them both, and then click the "Apply style settings" button again.
Please let me know if it works as you expect now, or if there are stille some issues.
