### ISSUE TITLE
[Bugs or maybe Feature Request]Published Page url non-english(chinese) alphabet missing

### ISSUE THREAD

**Issue by imfannet** [oleeskild/obsidian-digital-garden#46]
What happend:
1. Write a page with non-english alphabet title and content (which is actual Chinese)
2. set dg-publish: true
3. Publish the page
4. Open the Published Page.
5. In the URL, non-english alphabet content missing but the english part exist.
6. In the page content, all working fine.

The page published(With Copy Garden URL command）: https://note.imfan.net/work/the-test-page-of-digital-garden-test/
The full title: The test page of digital garden 中文页面 test

Didn't test other non-english alphabet content, but can confirm the Chinese won't work.

**Comment by hxhc** [comment]
是这样的，如果要在URL显示中文，可以试试[添加 dg-permalink](https://github.com/oleeskild/digitalgarden/issues/2#issuecomment-1063871117)

**Comment by Ravenclawer** [comment]
![image](https://user-images.githubusercontent.com/73892411/199022052-b762c24c-142d-403e-9265-7fde73df8358.png)
I don't see any problem with this test page, is this issue already been solved?

**Comment by oleeskild** [comment]
Good news! A fix for this has been introduced in the latest release. I've released version 2.27.0 of the plugin which lets you disable "Slugify URL". I've created a page in the docs here: https://dg-docs.ole.dev/getting-started/05-other-settings/#slugify-note-url.
Disabling this should fix your issue 😄
