### ISSUE TITLE
Mark empty links

### ISSUE THREAD

**Issue by reznikdn** [oleeskild/obsidian-digital-garden#47]
Hello! Thank you a lot for your plugin!
I just wanted to ask if there is a way to mark empty links on the site (by color, for example)? If not, is it possible to make such a function? This would be very useful, because for privacy reasons, it is often necessary to publish only certain notes. And it is quite problematic to delete on each note links to other notes that you are not planning to publish. If you could help with this problem (or suggest how it is possible to solve it by myself), I would be very grateful to you!

**Comment by oleeskild** [comment]
Hi!
Thanks for the suggestion. I've implemented this feature in the[ latest release](https://github.com/oleeskild/digitalgarden/releases/tag/1.13.0) of the template. I've added some default styling. If you want to override it with your own styling you can add a "a.is-unresolved{}" css rule to the "src/site/styles/custom-style.scss" file. 

You can update it by going to Obsidian settings > digital garden > manage site template > create pr. You will then be presented with a link after about 20 seconds. Clicking this lets you complete the pull request and merge the latest changes into your repository.

Let me know if this solved your problem.

**Comment by oleeskild** [comment]
I had a look in your repository and it seems you haven't completed the PR updating the template: https://github.com/reznikdn/digitalgarden_thesis/pull/1

If you complete that, you should be able to apply the new css rule.

**Comment by oleeskild** [comment]
Wonderful!
