### ISSUE TITLE
[Feature request] Let users set a main language for their digital garden

### ISSUE THREAD

**Issue by stalegjelsten** [oleeskild/obsidian-digital-garden#472]
All web sites **should always** include the main language of the site declared in the html element, such as: `<html lang="en">`. For reference, plase see [https://www.w3schools.com/tags/ref_language_codes.asp](https://www.w3schools.com/tags/ref_language_codes.asp). 

In its current implementation, the main language for all digital gardens is set to english. This is a problem for digital gardens written in other languages.

I propose to let the user choose their main language (defaulting to english `en`).

**Comment by dayne** [comment]
House keeping comment to tie together current state of things on this PR (and #471)  
Looking further back it appears this, #471  and #213 are effectively the same feature request for being able to set the language.

@stalegjelsten has offered up a two PRs for this topic:
-  https://github.com/oleeskild/digitalgarden/pull/208/files
  In website template it adds the use of a `site.mainLanguage` to set the `<html lang="{{ meta.mainLanguage }}">`
   mainLanguage: process.env.SITE_MAIN_LANGUAGE || "en",
-  #473 
  For the Obsidian plugin it adds `mainlanguage` as a concept that can be set and passed over as an ENV variable for website.
