### ISSUE TITLE
Stuck on "Calculating publication status from Github"

### ISSUE THREAD

**Issue by BahneGork** [oleeskild/obsidian-digital-garden#477]
When hitting the digital garden button, the popup is stuck on a rotating gear with the text calculating publication status from github.

**Comment by oleeskild** [comment]
There was a bug in a recent release of the plugin, where if you had a default branch not named "main", the publication center would load forever. The latest release should fix this, let me know if updating the plugin fixes your problem.

**Comment by BahneGork** [comment]
I fixed it by renaming my branch from master to main.
