### ISSUE TITLE
Unable to publish

### ISSUE THREAD

**Issue by xinyi-li7** [oleeskild/obsidian-digital-garden#487]
To whom it may concern, 
  I've followed all the steps in this [getting-started](https://dg-docs.ole.dev/getting-started/01-getting-started/) blog to establish my digital garden, however, every time I tried to publish a single note, it always gives "Unable to publish note, something went wrong". I've start a new git repo and vercel project but still, getting this error. Can anyone help me debug this issue? Is there a way I can provide the log info to help you debug this issue? Thank you so much! 
<img width="760" alt="image" src="https://github.com/oleeskild/obsidian-digital-garden/assets/69008042/5c783a93-5e4a-454f-b4f3-c3210ee214a2">

**Comment by xinyi-li7** [comment]
Hi @oleeskild , thanks for your reply! I just got the error message and pasted it here. 
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/69008042/9b5847f8-eedf-49a9-8751-9f75085c6c1c)
It seems there is a deprecated package is used. 
Thank you!

**Comment by ifyouseewendy** [comment]
I ran into the exact same error. Thanks @xinyi-li7 for pointing out the direction for the probable conflicts with Dataview. I'm able to publish notes after upgrading the Dataview plugin to the latest version (0.5.64) now.
