### ISSUE TITLE
selecting custom favicon will throw build error (deploy via netlify)

### ISSUE THREAD

**Issue by efemkay** [oleeskild/obsidian-digital-garden#495]
i already has my digital garden site running via netlify. but whenever i try to change the favicon (via the plugin's settings), the build will throw this error. if i change it back (delete the custom favicon from the plugin settings), it will be okay again.

so i assume it's the favicon issue and the build log seems to suggest so. i'm not that fluent in reading the build log, so let me know if there's additional things u need from the log

![image](https://github.com/oleeskild/obsidian-digital-garden/assets/42369515/17099e67-1489-4713-ad34-eb24175693a8)

**Comment by dayne** [comment]
Sounds like your favicon is not square. Have you tried another custom favicon? Can you double check the one you are using is actually square?  Perhaps link/attach it here so others can test/verify using it.

**Comment by efemkay** [comment]
huh. i know the error msg says so but i just could not figure out if my svg is square or not. looking at it (attached below) it seems to be square. i'm on windows and right click properties an svg does not give any info about the svg dimension (understandable since svg is scalable) or aspect ratio.

but after reading your reply, i remember that svg is somewhat readable string of text. i open it in notepad instead. lo and behold, i see the viewbox is `216.000` and `219.000`. visually square but not to computer.

I've managed to square it and yes, managed to get the favicon reflected in the published site. thanks for being a good sport. sometimes just need a 2nd person to help see the light

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
 "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="216.000000pt" height="219.000000pt" viewBox="0 0 216.000000 219.000000"
 preserveAspectRatio="xMidYMid meet">
<metadata>
Created by potrace 1.10, written by Peter Selinger 2001-2011
</metadata>
<g transform="translate(0.000000,219.000000) scale(0.100000,-0.100000)"
fill="#2f4f4f" stroke="none">
<path d="M635 2140 c-148 -30 -265 -85 -367 -175 -60 -54 -147 -163 -178 -224
-77 -153 -82 -208 -78 -727 4 -400 5 -422 26 -484 88 -261 305 -458 562 -512
79 -17 827 -23 900 -8 188 40 297 99 421 227 77 79 114 133 153 220 54 124 57
165 54 653 -3 442 -3 445 -27 515 -69 197 -213 363 -393 451 -63 30 -92 39
-203 64 -49 11 -814 11 -870 0z m615 -480 c91 -23 109 -29 165 -55 81 -39 160
-100 175 -135 10 -25 10 -34 -4 -55 -20 -30 -58 -47 -83 -38 -10 4 -44 25 -76
46 -89 60 -182 94 -293 107 -285 31 -459 -71 -429 -253 10 -58 64 -106 144
-129 48 -14 99 -18 247 -18 179 0 189 -1 211 -22 31 -29 30 -71 -2 -96 -22
-18 -46 -20 -252 -24 -206 -4 -232 -6 -268 -25 -84 -44 -121 -112 -108 -198
11 -73 56 -122 143 -156 48 -19 75 -22 205 -22 176 -1 254 14 390 74 50 21 96
39 104 39 25 0 61 -42 61 -70 0 -45 -71 -100 -172 -134 -106 -36 -189 -49
-341 -54 -172 -5 -252 7 -352 53 -127 59 -205 166 -205 283 0 95 63 204 144
247 20 11 36 25 36 32 0 7 -20 28 -45 47 -61 46 -80 72 -100 134 -31 94 -3
210 71 292 68 75 181 127 304 140 84 9 276 3 330 -10z"/>
</g>
</svg>

```

![myfavicon](https://github.com/oleeskild/obsidian-digital-garden/assets/42369515/e19e6769-6d21-4c3e-9955-56285410bacf)
