### ISSUE TITLE
using analytics

### ISSUE THREAD

**Issue by Windshield-Viper** [oleeskild/obsidian-digital-garden#505]
how would I use analytics from Vercel, Google, or Goatcounter on my garden?

**Comment by dayne** [comment]
Take a look at this thread to see if you find the answer here:

https://github.com/oleeskild/obsidian-digital-garden/discussions/195

If you do perhaps take notes and share to help augment any details needed so docs can be updated.

**Comment by Windshield-Viper** [comment]
I managed to use GoatCounter Analytics by simply editing the index page (editing index.njk) and then re-building the site.
