### ISSUE TITLE
Pages only get deleted a few at a time

### ISSUE THREAD

**Issue by wheresalice** [oleeskild/obsidian-digital-garden#512]
I did a major restructuring of my folders, leading to many pages needing to be deleted and recreated

The new pages were created fine, but deleting isn't working as expected. Every time I "Publish Selected" it tells me it has published all changes, but it actually only publishes one to three changes and I have to keep going through the publish process until the number reaches zero

**Comment by LespiletteMaxime** [comment]
I confirm, it did the same to me

**Comment by Luo-hongyi** [comment]
I'm tired of only deleting one file per publishing.

**Comment by josuantonsanz** [comment]
It seems easier to delete the contents of src and then let the plugin reupload every file it needs.

**Comment by Luo-hongyi** [comment]
> It seems easier to delete the contents of src and then let the plugin reupload every file it needs.

how to? clone to local and delete src, then push?

**Comment by josuantonsanz** [comment]
> > It seems easier to delete the contents of src and then let the plugin reupload every file it needs.
> 
> how to? clone to local and delete src, then push?

I did it the "easy" (or noob) way, just from the github page. I deleted there the content and push from the same page.

**Comment by oleeskild** [comment]
Release 2.56.1 should fix this 😄
