### ISSUE TITLE
Moved note showing in multiple places

### ISSUE THREAD

**Issue by creativefibro** [oleeskild/obsidian-digital-garden#524]
![Duplicate folders](https://github.com/oleeskild/obsidian-digital-garden/assets/39191327/caa73ce3-c09b-462a-94c8-b2d035fa77d7)

I initially created an Obsidian Folder Called Digital Garden and put my first three notes in it. I then decided that I wanted my published notes to remain in their natural places in my vault. 

I moved the first three notes out however My Current App stack is showing in it's new folder and also the  Digital Garden folder. However in my Obsidian vault the Digital Garden folder has been deleted and the note is only in the correct Efforts folder. 

I can't find a way to correct this.

**Comment by Luke-zhang-04** [comment]
Looks like the delete functionality of the plugin is deleted. The problem is that the note is no longer in your Obsidian vault, but it hasn't been deleted from your site repository.

**Comment by creativefibro** [comment]
No it was the folder that was deleted the note was just moved. I resolved it in the end by un-publishing it and publishing all notes. Then publishing it again. The removed folder and duplicate note disappeared then. I guess it was some sort of glitch.
