### ISSUE TITLE
Transclusion to only a part of the note aren't supported

### ISSUE THREAD

**Issue by samur-netizen** [oleeskild/obsidian-digital-garden#54]
Transclusion to part of the note aren't supported and show full note instead, so syntax like:
- ![[Note#NoteHeading]] will show full Note as transcluded instead of only part of this note concerning NoteHeading
- ![[Note#^fc5f29]] will show full Note as transcluded instead of only part of this note concerning some paragraph or callout.

Do you think you can support it? I use transclusions a lot and without that feature it's hard for me to share my notes.

**Comment by oleeskild** [comment]
I actually wasn't aware that this was possible in Obsidian. Very cool. 
I will look into it. If the obsidian APIs make it easy to retrieve sections from a note this should be easy to implement. However if I need to "calculate" sections myself it would be a bit more work. I'll add it to my todo list!

**Comment by hxhc** [comment]
I also encountered this issue. Hope it's not difficult to solve.

**Comment by shmuga** [comment]
PR #78 resolved Heading transclude. Not sure what the second syntax means

**Comment by mettaseva** [comment]
+1 since I use anchor links quite frequently, too. Thanks!

**Comment by oleeskild** [comment]
Version [2.29.0](https://github.com/oleeskild/obsidian-digital-garden/releases/tag/2.29.0) has just been released, which adds support for transcluding blocks by anchor tag. 
Thanks to @uroybd for implementing this feature.

**Comment by jacobmercy** [comment]
The original transclude seems to be appearing as regular, unlinked text.

In Obsidian, it appears as linked and superscripted.

**Comment by uroybd** [comment]
> The transclusion source number (^123a4b) seems to be appearing as regular, unlinked text.
> 
> In Obsidian, it appears as linked and superscripted.

Hi, This is being handled in #141 However, in this case, I'm not superscribing, instead converting it as the id for that block in HTML so it can be linked, just like obsidian.

**Comment by oleeskild** [comment]
@jacobmercy , as @uroybd mentioned this has been fixed in the latest version. The ^123abc number will now disappear, but linking to it will still work.

**Comment by SemanticBeeng** [comment]
This
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/9296536/8118c2e9-d850-4143-982b-8e7198afcd83)

Render this way (correctly) in `Obsidian` **1.3.5**
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/9296536/c39a8fdc-b265-44ab-a11a-2a4093a78d9a)

but renders this way in `Digital Garden` **2.45.2**
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/9296536/59a5fda1-bce4-47f2-bae4-dde77cf47a79)

Is this the defect that was supposed to be solved or a different one?

**Comment by uroybd** [comment]
> This ![image](https://user-images.githubusercontent.com/9296536/258574352-8118c2e9-d850-4143-982b-8e7198afcd83.png)
> 
> Render this way (correctly) in `Obsidian` **1.3.5** ![image](https://user-images.githubusercontent.com/9296536/258574396-c39a8fdc-b265-44ab-a11a-2a4093a78d9a.png)
> 
> but renders this way in `Digital Garden` **2.45.2** ![image](https://user-images.githubusercontent.com/9296536/258574466-59a5fda1-bce4-47f2-bae4-dde77cf47a79.png)
> 
> Is this the defect that was supposed to be solved or a different one?

It is kind of a defect. Will try to fix it.
