### ISSUE TITLE
Dataview output is not rendered correctly

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#57]
Hello guys!

Firstly: Awesome plug-in! ❤️ This was exactly what I was looking for. 😄

ℹ️ Regarding my issue:
I would like to automatically create a list of all notes in a specific folder (i.e. list of internal links). To avoid linking each file separately.
I solved this using dataview and the following query: `dataview list from "21 Homepage Wordpress"` which displays the list of links just fine in Obsidian.

⛔ Problem: Please visit _www.alberer.contact_ in the middle of the page you will find the following section:

![image](https://user-images.githubusercontent.com/61867589/179394650-4c7095d5-5e9d-4832-9c64-c31d87186913.png)

But of couse instead of `list from "21 Homepage Wordpress"` I would like links to notes of above specified folder to appear.

Did I do something wrong or can this dataview query just not be rendered correctly with dg?
(If so, do you have a solution?)

Thanks!

**Comment by oleeskild** [comment]
Hey 👋 
Thank you, happy to hear you like it 😄 

There are several issues asking for this feature (#7 #43). Until now it has not been supported, as I could not figure out a good way to implement it. 
However,  the author of dataview recently shipped a new feature, allowing me to easily render markdown from dataview queries. So I've just shipped [version 2.14.0 ](https://github.com/oleeskild/obsidian-digital-garden/releases/tag/2.14.0) of the digital garden plugin, which adds support for this. Note that you need at least version 0.5.39 of the dataview plugin for this to work properly. Let me know if it's working as expected for you now.
