### ISSUE TITLE
SVG resizing isn't working

### ISSUE THREAD

**Issue by keerah** [oleeskild/obsidian-digital-garden#58]
Thanks so much for fixing the SVG image support, but the resizing tag like `![[img.svg|256]]` or `![img|256](img.svg)` isn't currently working with SVGs

**Comment by keerah** [comment]
Sorry for bumping, but I still miss this small feature a lot

**Comment by oleeskild** [comment]
It's a bit overwhelming with all the issues posted, and it's not always easy to prioritize them. So bumping a feature request is a good way to let me know if something is important, and remind me that it exists. So no worries! 

I've released version 2.25.0 of the plugin, which has added support for this. 

Note that you will only need to update the plugin itself, not the template.

**Comment by oleeskild** [comment]
I realized I had forgot to add support for the second syntax you mentioned. I've released version 2.25.1 which adds support for that as well.
