### ISSUE TITLE
[Feature Request] Style Settings Support

### ISSUE THREAD

**Issue by Dhruvsr** [oleeskild/obsidian-digital-garden#59]
Hello, I am requesting a **feature** which includes support for **Style Settings**, a plugin frequently used with popular themes such as Prism.
This would make customization of the digital garden seamless.

Thanks!

**Comment by oleeskild** [comment]
That would be really cool, and make the plugin more accessible for people who don't know how to write their own CSS. I will look into if this is possible to implement somehow. Thanks for the suggestion!

**Comment by oleeskild** [comment]
This has finally been implemented in the latest release of the plugin and template. It's described how to use it here: https://dg-docs.ole.dev/getting-started/04-appearance-settings/#style-settings-plugin

**Comment by sanderdatema** [comment]
Could it be that it doesn't work for all themes? For example, when applying settings for the PLN theme, nothing is added to the git repo.
