### ISSUE TITLE
Images added to Git in /img/user/img/user/ should be in /img/user/ only

### ISSUE THREAD

**Issue by ashl1** [oleeskild/obsidian-digital-garden#605]
1. Added image in the article by `![[MYIMAGE.png]]`
2. Image was uploaded in `src/site/img/user/img/user/MAINDIR/SomeOtherName/MYIMAGE.png` in a git repo
3. In a site the code is `<picture src="f/img/user/img/user/MAINDIR/SomeOtherName/MYIMAGE.png" ...`

Plugin version: 2.57.1

**Comment by oleeskild** [comment]
Thanks for reporting this, it should be fixed in release 2.57.2
