### ISSUE TITLE
fonts are not found in my repo and anywhere

### ISSUE THREAD

**Issue by abbychau** [oleeskild/obsidian-digital-garden#61]
![image](https://user-images.githubusercontent.com/350283/180929110-664f5f12-ea85-4d56-a876-bb053a124344.png)

how to resolve it?

**Comment by oleeskild** [comment]
Hi
Can you post some more information? It would be helpful to get a link to your site, as well as info about whether you have applied a custom theme or any other custom settings related to fonts. Thanks!

**Comment by abbychau** [comment]
I am using the default theme.

here are the lint and the repo:

https://bm.abby.md/

https://github.com/abbychau/digitalgarden

**Comment by oleeskild** [comment]
This should have been fixed now. If you update the plugin and the template to the latest version, the fonts should be loaded correctly.
