### ISSUE TITLE
Dataview Remove Broken Links

### ISSUE THREAD

**Issue by wchorski** [oleeskild/obsidian-digital-garden#619]
When using `dataview` to list recently updated notes, it looks like non published notes are listed as well.

Is there any way to either 

1. skip over unpublished notes
2. remove broken links

## Dataview Example
```dataview
TABLE dateformat(file.mtime, "dd.MM.yyyy - HH:mm") AS "Last modified"
FROM "mynotes"
SORT file.mtime DESC
LIMIT 10
```
## What the Published site looks like
<img width="954" alt="image" src="https://github.com/user-attachments/assets/c1d50881-2e38-42fd-9aa0-06d7759d6711">

all broken links point to `https://pywrite-garden.tawtaw.site/404/`

**Comment by stalegjelsten** [comment]
Hi @wchorski, adding `where dg-publish` to your Dataview query would probably fix this. 

```dataview
TABLE dateformat(file.mtime, "dd.MM.yyyy - HH:mm") AS "Last modified"
FROM "mynotes"
WHERE dg-publish
SORT file.mtime DESC
LIMIT 10
```

---

If you would like to have all your notes listed in Obsidian, but only show the published notes in the dataview tables in your digital garden you can use the following "hack".

In your dataview queries, add a line containing `WHERE file.mtime` in a separate line, e.g.

```dataview
TABLE dateformat(file.mtime, "dd.MM.yyyy - HH:mm") AS "Last modified"
FROM "mynotes"
WHERE file.mtime
SORT file.mtime DESC
LIMIT 10
```

(It doesn't need to be `file.mtime`, but choose something which matches all notes, but at the same time is not something you would ever add an actual where filter for).

Then you can use a Digital garden custom filter which replaces `WHERE file.mtime` with `WHERE dg-publish` 👇
<img width="621" alt="image" src="https://github.com/user-attachments/assets/b31088f2-c635-432a-b06d-321a39afe3fe">

**Comment by wchorski** [comment]
Thank you. This is exactly what I needed. The flexibility of having my dataviews in my local vault vs my garden can be reflected or filtered on publish lets me do whatever I want per dataview. 

Also, this gives me more ideas on how to use custom filters. (i'm gonna put this tip in my vault too)
