### ISSUE TITLE
Will this amazing plugin support Dataview?

### ISSUE THREAD

**Issue by hxhc** [oleeskild/obsidian-digital-garden#7]
I tried your brilliant plugin, it works so amazingly. Thank you!

And I have an natural idea. In the homepage (the note with dg-home: true) I use the dataview plugin to list all the notes published. But the dataview seems not be supported. It is shown [below](https://hxhc-notes.netlify.app).
![image](https://user-images.githubusercontent.com/13412966/157403960-53613edd-1789-4631-ab0f-aad88db17271.png)

I know that the current support content does not include dataview, but I truly hope this could be realized. If supporting dataview costs a lot of time, just ignore my issue. Because this plugin is good enough already.

**Comment by oleeskild** [comment]
Thank you for your kind words!

I agree, supporting dataview would be amazing, and open up tons of possibilities for customization. 
I'm currently looking into this to see if this will be possible. I suspect it will be complex to get right. I'll report back on this issue when I've done a bit more research.

**Comment by oleeskild** [comment]
Great news @hxhc . The Dataview API was recently updated with functionality to render markdown from a dataview query. I've just release version 2.14.0 of the digital garden plugin which add support for rendering dataview queries. Note that you need at least version 0.5.39 of the dataview plugin for this to work properly.

**Comment by hxhc** [comment]
This is fantastic. I just updated the new version, and it is quite good. Thank you and the Dataview author so much for your plugins❤.
