### ISSUE TITLE
Remove ribbon command

### ISSUE THREAD

**Issue by Calorion** [oleeskild/obsidian-digital-garden#70]
Is there a way to remove the ribbon command for this plugin?

**Comment by Calorion** [comment]
Please? I keep hitting "Help" when I'm trying to hit "settings" because the Digital Garden icon takes a second to load and shifts my other ribbon icons down.

**Comment by oleeskild** [comment]
@Calorion I've released a new version, 2.15.0, which adds a new setting letting you toggle this on an off. Note that you need to reload obsidian for the changes to take effect.
