### ISSUE TITLE
[Feature Request] Support for dyanamic toc (Table of Contents)

### ISSUE THREAD

**Issue by Dhruvsr** [oleeskild/obsidian-digital-garden#73]
The [*Dynamic Table of Contents Plugin*](https://github.com/Aidurber/obsidian-plugin-dynamic-toc) is quite useful when creating indexes for notes.
Is it possible to have the digital garden utilizing this plugin?
Here is a __[**demonstration**](https://dhruv.is-from.space/1664099045.png)__ of how I currently use it.

**Comment by oleeskild** [comment]
Supporting this would be really cool. Thanks for the suggestion, I'll add it to my todo list 😄

**Comment by meleu** [comment]
That would be indeed a neat feature (to have the ToC being **dynamically** generated).

As a workaround, I'm using the [Table of Contents plugin](https://github.com/hipstersmoothie/obsidian-plugin-toc), that creates a static ToC.

**Comment by mettaseva** [comment]
+1 for note TOC, for those of us who write long notes :-)

**Comment by f-mc2** [comment]
What about the possibility of laso having the TOC in a dedicated frame similarly to backlnks and graph?

**Comment by oleeskild** [comment]
I have a working version of this, but I need to figure out how it should look in combination with the other elements. 
I think it looks best when put on the top right. But it gets a bit crowded in the right pane if the local graph and the backlinks are also enabled.
I'm thinking that I should perhaps move the backlinks pane to somewhere else on the page...

Does anyone have any suggestions of what would look best?
Here is a GIF of the current version: 
![CleanShot 2022-12-07 at 13 41 53](https://user-images.githubusercontent.com/6201338/206182955-1eb0724a-7408-4341-862c-56cceb52d2fa.gif)

**Comment by mettaseva** [comment]
Another quick question about this implementation. Will the creation of this TOC panel provide an option for us to access/share section header anchor links?

This anchor links feature is also available in Obsidian.md and FeatherWiki.

**Comment by oleeskild** [comment]
Really appreciate your feedback @mettaseva . You make some very good arguments for having the ToC beneath the graph. I went for that option. I've just released a new version and table of content is now available as a setting in the plugin. Remember to first update the plugin before updating the template 😄

**Comment by meleu** [comment]
@oleeskild 
I've created the PR to my template and got a deploy failure of the preview. Looks like the `./src/helpers/utils` is missing.

![image](https://user-images.githubusercontent.com/8508804/208135107-87731027-5f5c-48cc-98a2-11ba1d9148b1.png)

**Comment by oleeskild** [comment]
You will need to update the plugin to the latest version first. Try that and see if it works then.

**Comment by meleu** [comment]
great! that did the job!

thanks! :heart:
