### ISSUE TITLE
[Fix] Prevent ^b7cefc showing for linked headings

### ISSUE THREAD

**Issue by Dhruvsr** [oleeskild/obsidian-digital-garden#75]
When I link headings on Obsidian, they appear like this:
![image](https://user-images.githubusercontent.com/48249839/195145763-f5e11c29-4812-4a2d-9567-3b5d0a1addd4.png)
However, on published notes, rather than hiding the ^ffe8e3 tag, it appears on the digital garden as well in text form:
![image](https://user-images.githubusercontent.com/48249839/195145971-03e6cd5e-e1e3-46c0-a23c-c29a446bb2cf.png)
Could this be fixed in some way?

**Comment by mettaseva** [comment]
Just wondering if **[THIS](https://github.com/oleeskild/obsidian-digital-garden/issues/54)** is the same issue, by any chance?

**Comment by oleeskild** [comment]
This has been fixed in the latest version. It will now disappear, but linking to it, either as a transclusion or as a regular wikilink ([[My Note#^b7cefc]]) will still work, and link the user to that specific block.
