### ISSUE TITLE
Permanent Sidebar for Local Graph and Backlinks

### ISSUE THREAD

**Issue by zcysxy** [oleeskild/obsidian-digital-garden#76]
Huge thanks for this amazing plugin! I've always wanted to publish my notes, but most alternatives are complicated or missing some key features. With this plugin, I set up the website in 5 mins and can directly publish notes in Obsidian on the fly!

I have some small feature requests. Can there be an option to make the sidebar for the local graph and backlinks be permanent rather than togglable? Just like [help.obsidian.md](https://help.obsidian.md/Obsidian/Index), this will provide more info and help navigation.

Also, the local graph doesn't show the neighbor links or the direction. I think these elements will make the local graph more useful.

**Comment by zcysxy** [comment]
Thanks for the implementation! It looks perfect!

On my end, the right sidebar and the note content overlap a little bit. Thus I added this snippet to my `custom-style.scss`:

```css
div.content { max-width: 800px; }
```

**Comment by oleeskild** [comment]
You're right, thanks for telling me. The specific note that I tested with yesterday didn't have that problem. 
I've released a patched version with your change.

**Comment by oleeskild** [comment]
Closing this, as the permanent sidebar has been implemented. Created a new issue regarding the neighbouring links: #148
