### ISSUE TITLE
Show  inline title have more space

### ISSUE THREAD

**Issue by oyes77** [oleeskild/obsidian-digital-garden#79]
![image](https://user-images.githubusercontent.com/53545025/196067525-852dd95b-f313-4852-9e78-3f5b3cf56fc4.png)

Right now the inline title doesn't have enough space under it for my liking, and i think for most people too, maybe adjust it to have 2 lines separating it from the note?

**Comment by oleeskild** [comment]
The title is just a h1 tag. The space between that header and the content is determined by whatever theme you are using on your site. You can override it by setting a rule in the custom-style.scss file. For example: 
```css
h1 {
  margin-bottom: 10px;
}
```
