### ISSUE TITLE
Support highlights and footnotes

### ISSUE THREAD

**Issue by toburger** [oleeskild/obsidian-digital-garden#8]
I'm using highlighting and footnotes on my notes and it seems the features aren't supported.
_It looks like the highlighting feature isn't supported in GitHub neither, but the footnotes seem working partially._

## Highlighting

```md
Use two equal signs to ==highlight text==.
```

Use two equal signs to ==highlight text==.

## Footnotes

```md
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: meaningful!

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.
```

Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: meaningful!

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.

You can also use inline footnotes. ^[notice that the carat goes outside of the brackets on this one.]

**Comment by oleeskild** [comment]
Great input! I've released a new version of the template that add support for this (https://github.com/oleeskild/digitalgarden/releases/tag/1.7.0). You can update your template by using the "Create PR" button in the digital garden setting in obsidian. Let me know if it works as you expected!

**Comment by toburger** [comment]
Worked like a charm! Thank you!
