### ISSUE TITLE
"Show inline title"

### ISSUE THREAD

**Issue by Calorion** [oleeskild/obsidian-digital-garden#81]
So Obsidian has a great new feature called "Show inline title," which I love. But this creates a problem with Digital Garden, because now I have to choose between having two titles showing when I view my digital garden in my vault, or not having the H1 show up online. 

Could we have a setting which, when "Show inline title" is on, will insert the title into the web page?

**Comment by oleeskild** [comment]
I quickly encountered the same issue when upgrading to Obsidian 1.0. 
It is already implemented and was released in version 2.18.0 😄 
You can either enable it globally via "Settings > Digital Garden > Note Settings > Edit" or on a per-note basis using this tag in the frontmatter: dg-show-inline-title: true.

But I realise I haven't added this to the readme. I'll add it right away. Thanks for reminding me.

**Comment by Calorion** [comment]
This doesn't seem to be working for me. When I turned this setting on, removed the H1 from my document, and re-published, the H1 vanished from the web page.

**Comment by Calorion** [comment]
That plugin has been removed from the Obsidian app store and archived, so it's built-in or nothing from now on, I'm afraid!

**Comment by Calorion** [comment]
Okay, this only seems to be happening on the home page. Other pages _do_ have the H1 show up.

**Comment by Calorion** [comment]
Still not working with my home page, even with it specifically enabled in the frontmatter.

**Comment by oleeskild** [comment]
Thank you for reporting this. This was a bug. I've fixed it in version 1.17.4 of the template

**Comment by vitry** [comment]
I used Minimal theme dark schema and enabled "dg-show-inline-title", but it didn't work.
