### ISSUE TITLE
[Feature]: Link previews

### ISSUE THREAD

**Issue by shmuga** [oleeskild/obsidian-digital-garden#83]
I kind of like when obsidian gives me link previews when you hover over them. It speeds up the interactions a bit and makes it much simpler to navigate long list of links.

I have this implemented in my website template and if that’s somethings worth porting I could create a PR later. The implementation is very straightforward: add handlers to all links on mouseenter and show the `iframe` using  https://popper.js.org/. I chose popper cause it very lightweight and powerful in terms of showing pop ups.

**Comment by oleeskild** [comment]
The option to enable link preview would be great. That is a really clever way to do it. If you find the time to create a PR for this it would be very much appreciated!

**Comment by mettaseva** [comment]
+1 ~ This is very helpful, user-friendly features for notes with lots of links.

**Comment by keerah** [comment]
Yes please, I miss this too

**Comment by oleeskild** [comment]
I don't think this is as easy as before. Previously all the pages only had the content. Now that you can add things like the filetree, the graph and backlinks, it would look weird in an iframe.

I think we have two options:
1. Iframe it as is, but make sure the width is that of a mobile screen. We still get the navbar up top, but it would be an easy implementation
2. Add a query variable that is picked up by javascript, and disables every element that is not part of the content.
3. Add a new template with a url that has some pre- or postfix to the normal note url, that generates the notes without all the extra UI elements around, and use that for the iframe source. Then it would look nice. But it could be a problem for SEO. Maybe as long as it isn't being added to the sitemap.xml file, and not a part of the file tree it should be fine. Perhaps also adding it to a robots.txt would be good enough. I would have to look more into it to be sure.

**Comment by oleeskild** [comment]
I had quick a look at how the [Digital Garden Jekyll Template](https://github.com/maximevaillancourt/digital-garden-jekyll-template) implemented this feature. They have a very elegant solution, where they load the link in an iframe that's invisible, before pulling only the content from that iframe an putting it in a div to display. I've used the same approach, and released a new version of the plugin that support link previews. 

Remember to FIRST update the plugin, then update the template to the latest version to use this feature.
