### ISSUE TITLE
Why toggleOpen() is not defined on some pages?

### ISSUE THREAD

**Issue by zcysxy** [oleeskild/obsidian-digital-garden#85]
Some pages don't have the toggle for right sidebar. And the console says `toggleOpen()` is not defined. An example: https://edav-garden.netlify.app/q-q-plot/

**Comment by oleeskild** [comment]
Thanks for reporting this! I believe I squashed the bug in the [latest template release](https://github.com/oleeskild/digitalgarden/releases/tag/1.18.2). Could you update the template, and report back on whether the fix worked for you or not?

**Comment by zcysxy** [comment]
Yes, the problem is gone, thanks!
