### ISSUE TITLE
so, i can't upload anything...

### ISSUE THREAD

**Issue by oyes77** [oleeskild/obsidian-digital-garden#86]
It started when i made a pull request to update, and updated the site, then the themes problem that came with newer obsidian versions that was commented in other issue 13 days ago, at the time i write this, and any try to update the theme failed, now it's every update to the page in general, it fails so i'm stuck

![image](https://user-images.githubusercontent.com/53545025/198900156-6f39543a-e59b-4b63-901f-ce8279bf2a41.png)
rhar's what netlify shows, from obsidian it just says updated correctly

**Comment by oyes77** [comment]
![image](https://user-images.githubusercontent.com/53545025/198900207-59a1681b-caf9-4367-96b7-4919b65256df.png)
![image](https://user-images.githubusercontent.com/53545025/198900228-5262995f-1b8f-4434-ae2e-cb109e7662b7.png)
everything seems to be normal, i'm not really fluent on github or development in general but i don't see anything broke, what do i do?

**Comment by oyes77** [comment]
that's the error part of the first time i couldn't update the page
![image](https://user-images.githubusercontent.com/53545025/198900338-5656db8d-97b7-4dd7-8093-7ec3c86f44ba.png)

**Comment by oyes77** [comment]
update: tried to make a pull request to update to latest template, didn't work either:
![image](https://user-images.githubusercontent.com/53545025/198901678-e8ba5d03-ebe4-4882-b3be-7b0fe34fc8cb.png)
the error is a missing "{" by the looks of it...(?

**Comment by oyes77** [comment]
by some troubleshooting i think it's just custom.css doing weird stuff, since i edit it too much, i'll just reset it, and close the issue if that was the problem, sorry if this was annoying

**Comment by oleeskild** [comment]
Given your screenshots it seems you were either missing, or had one to much "{" or "}" in your custom-style.scss file somewhere. Glad to hear you solved it 👍
