### ISSUE TITLE
Note Settings are not propagating

### ISSUE THREAD

**Issue by thorms11** [oleeskild/obsidian-digital-garden#87]
I have most of the note settings toggled on and I am not seeing them on the garden. 

[Settings](https://drive.google.com/file/d/1nbZLavuMSgBl2MUm0Iu5BW6TzRx9JXiz/view?usp=sharing). [Actual site](https://folkvangr.netlify.com/).

**Comment by oleeskild** [comment]
There was recently a change in how the note settings are handled. Previously you would need to re-publish every note when changing a note setting for it to take effect. Now it automatically applies to all without the need to republish. 
But in order for it to work you need the latest version of the template. 
If you go to Settings > Digital Garden > Site Template > Manage site template > Create PR, you should get a link to a Pull Request where you can merge in the latest changes. Then the settings should work. Let me know if you get it to work or not.

**Comment by thorms11** [comment]
Thanks for responding to this! This works perfectly!
