### ISSUE TITLE
[Bug] Collapsible callouts not rendering correctly

### ISSUE THREAD

**Issue by ThatOtherAndrew** [oleeskild/obsidian-digital-garden#89]
If you have a callout with a plus or minus symbol to denote a collapsible callout, like this:

```
> [!note]+ Example
> The plus character should not render!
```

Then the callout title appears as follows:
`+ Example`

I believe stripping the plus or minus and the space characters at the start should fix this issue.

**Comment by oleeskild** [comment]
Thanks to @Luke-zhang-04, this is now supported in the latest version. Remember to first update your plugin to the latest version, before [updating the template](https://dg-docs.netlify.app/getting-started/06-updating-the-template/)
