### ISSUE TITLE
Support files with the same file names

### ISSUE THREAD

**Issue by toburger** [oleeskild/obsidian-digital-garden#9]
When you have folders and you publish files with the same file name in it one of the two files get's replaced by the other file.

You can work around this issue by naming the files differently, but it would be very convenient to allow files with the same names.

**Comment by oleeskild** [comment]
Thanks for showing an interest in the project!

This should now be fixed in the latest plugin version. More info here: https://github.com/oleeskild/digitalgarden/issues/2

**Comment by toburger** [comment]
Very very nice! Thank you very much for the instant fix and I love your project so far!
