### ISSUE TITLE
[Bug] `dg-home-link: false` not working

### ISSUE THREAD

**Issue by Calorion** [oleeskild/obsidian-digital-garden#90]
I have a page with `dg-home-link: false` in the frontmatter, that nonetheless shows the home link if "Show home link" is turned on.

**Comment by oleeskild** [comment]
Right, I removed this when I implemented the new filetree, so it didn't really do anything. 
But I think it should still be possible to publish notes without showing the navigation bar on the top. So I've just released a new version where dg-home-link: false should result in the navigation bar on top to disappear. To make it work you'll first have to update the plugin to version 2.23.0, then update your template by using the "Create PR" button. Let me know if it works for you or not.
