### ISSUE TITLE
[Feature Request] Conversion before publish

### ISSUE THREAD

**Issue by zcysxy** [oleeskild/obsidian-digital-garden#92]
Is it possible to add a conversion script exposed to users, just like `custom-styles.scss`? This script converts the raw Markdown in Obsidian into a ready-publish Markdown, then passes it to the plugin. The script can be as simple as some **regex filters**.

Use cases: sometimes, there are parts of the note we don't want to publish, like **block-id**, metadata, comments, personal info, etc. And there may be special syntax in the note for plugins or personal use, but it is not readable on the published site. If we have a simple converter, we can strip the parts we don't want to publish and convert the special syntax to readable elements.

An example:

- Raw Markdown:

```markdown
- :warning: Pay attention to this line! ^a-block-id-for-embed
```

- Conversion regex:

```js
markdown = markdown.replace(/:warning:/gm, ($0) => "⚠️");
markdown = markdown.replace(/\^[a-zA-Z0-9-]*$/gm, ($0) => "");
```

- Ready-publish Markdown

```markdown
- ⚠️ Pay attention to this line!
```

**Comment by davidkopp** [comment]
I would love such a feature to be able to remove parts of a note I don't want to publish. For example, I include links to Zotero items in my notes, that are completely useless when published:

```markdown
[→Zotero](zotero://select/library/items/CMPPND8H)
```

It would also be sufficient for me to use regular expression for that.
