### ISSUE TITLE
How to disable navbar (for homepage)?

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#93]
Is there an option to disable the navbar on a per page basis (e.g. for the homepage)?

![image](https://user-images.githubusercontent.com/61867589/200398420-395b34b4-7e4e-4274-be63-d648b1680a06.png)

**Comment by oleeskild** [comment]
So you want your home page to show the filetree navigation sidebar, but not the top navigation bar when on mobile?
Or do you want to hide both the filetree navigation sidebar and the top navigation bar?
