### ISSUE TITLE
Folder side resets everytime i join a new file

### ISSUE THREAD

**Issue by oyes77** [oleeskild/obsidian-digital-garden#94]
![image](https://user-images.githubusercontent.com/53545025/200414577-12418065-9334-4cc6-96a0-1ae9efe721b1.png)
if i open a file, all the folders reset to their initial state (all closed with an exeption, i want for them to keep  however i have them between pages   (if i go to another folder, they don't change)

**Comment by oleeskild** [comment]
I agree, that would be much better user experience. I will need to find some way to keep that state across page reloads. I will look into it.

**Comment by OvrAp3x** [comment]
yes this would be great, 
created an issue for this before I saw this one, closed now (https://github.com/oleeskild/obsidian-digital-garden/issues/110)

**Comment by oleeskild** [comment]
I've just released version 1.21.0 of the template. The filetree should now remember the state that it's in across page reloads. The template can be updated by following the steps in the [documentation](https://dg-docs.netlify.app/getting-started/06-updating-the-template/). Let me know if it works as you expected 😄

**Comment by OvrAp3x** [comment]
Super Nice, working as expected!
